// Code generated by ent, DO NOT EDIT.

package proxyroutingrouteevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxyroutingrouteevent type in the database.
	Label = "proxy_routing_route_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReporterType holds the string denoting the reporter_type field in the database.
	FieldReporterType = "reporter_type"
	// FieldReporterID holds the string denoting the reporter_id field in the database.
	FieldReporterID = "reporter_id"
	// FieldProfileCode holds the string denoting the profile_code field in the database.
	FieldProfileCode = "profile_code"
	// FieldRoutingHash holds the string denoting the routing_hash field in the database.
	FieldRoutingHash = "routing_hash"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldRuleName holds the string denoting the rule_name field in the database.
	FieldRuleName = "rule_name"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldOutboundTag holds the string denoting the outbound_tag field in the database.
	FieldOutboundTag = "outbound_tag"
	// FieldDNSResolverTag holds the string denoting the dns_resolver_tag field in the database.
	FieldDNSResolverTag = "dns_resolver_tag"
	// FieldFallbackTarget holds the string denoting the fallback_target field in the database.
	FieldFallbackTarget = "fallback_target"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldEventAt holds the string denoting the event_at field in the database.
	FieldEventAt = "event_at"
	// FieldEventJSON holds the string denoting the event_json field in the database.
	FieldEventJSON = "event_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the proxyroutingrouteevent in the database.
	Table = "routing_route_event"
)

// Columns holds all SQL columns for proxyroutingrouteevent fields.
var Columns = []string{
	FieldID,
	FieldReporterType,
	FieldReporterID,
	FieldProfileCode,
	FieldRoutingHash,
	FieldEventType,
	FieldSubject,
	FieldRuleID,
	FieldRuleName,
	FieldActionType,
	FieldOutboundTag,
	FieldDNSResolverTag,
	FieldFallbackTarget,
	FieldStatus,
	FieldLatencyMs,
	FieldError,
	FieldEventAt,
	FieldEventJSON,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReporterType holds the default value on creation for the "reporter_type" field.
	DefaultReporterType string
	// ReporterTypeValidator is a validator for the "reporter_type" field. It is called by the builders before save.
	ReporterTypeValidator func(string) error
	// DefaultReporterID holds the default value on creation for the "reporter_id" field.
	DefaultReporterID string
	// ReporterIDValidator is a validator for the "reporter_id" field. It is called by the builders before save.
	ReporterIDValidator func(string) error
	// DefaultProfileCode holds the default value on creation for the "profile_code" field.
	DefaultProfileCode string
	// ProfileCodeValidator is a validator for the "profile_code" field. It is called by the builders before save.
	ProfileCodeValidator func(string) error
	// DefaultRoutingHash holds the default value on creation for the "routing_hash" field.
	DefaultRoutingHash string
	// RoutingHashValidator is a validator for the "routing_hash" field. It is called by the builders before save.
	RoutingHashValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultSubject holds the default value on creation for the "subject" field.
	DefaultSubject string
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultRuleID holds the default value on creation for the "rule_id" field.
	DefaultRuleID string
	// RuleIDValidator is a validator for the "rule_id" field. It is called by the builders before save.
	RuleIDValidator func(string) error
	// DefaultRuleName holds the default value on creation for the "rule_name" field.
	DefaultRuleName string
	// RuleNameValidator is a validator for the "rule_name" field. It is called by the builders before save.
	RuleNameValidator func(string) error
	// DefaultActionType holds the default value on creation for the "action_type" field.
	DefaultActionType string
	// ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	ActionTypeValidator func(string) error
	// DefaultOutboundTag holds the default value on creation for the "outbound_tag" field.
	DefaultOutboundTag string
	// OutboundTagValidator is a validator for the "outbound_tag" field. It is called by the builders before save.
	OutboundTagValidator func(string) error
	// DefaultDNSResolverTag holds the default value on creation for the "dns_resolver_tag" field.
	DefaultDNSResolverTag string
	// DNSResolverTagValidator is a validator for the "dns_resolver_tag" field. It is called by the builders before save.
	DNSResolverTagValidator func(string) error
	// DefaultFallbackTarget holds the default value on creation for the "fallback_target" field.
	DefaultFallbackTarget string
	// FallbackTargetValidator is a validator for the "fallback_target" field. It is called by the builders before save.
	FallbackTargetValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultLatencyMs holds the default value on creation for the "latency_ms" field.
	DefaultLatencyMs int
	// DefaultEventAt holds the default value on creation for the "event_at" field.
	DefaultEventAt func() time.Time
	// DefaultEventJSON holds the default value on creation for the "event_json" field.
	DefaultEventJSON string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProxyRoutingRouteEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReporterType orders the results by the reporter_type field.
func ByReporterType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterType, opts...).ToFunc()
}

// ByReporterID orders the results by the reporter_id field.
func ByReporterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterID, opts...).ToFunc()
}

// ByProfileCode orders the results by the profile_code field.
func ByProfileCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileCode, opts...).ToFunc()
}

// ByRoutingHash orders the results by the routing_hash field.
func ByRoutingHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingHash, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByRuleName orders the results by the rule_name field.
func ByRuleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleName, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByOutboundTag orders the results by the outbound_tag field.
func ByOutboundTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundTag, opts...).ToFunc()
}

// ByDNSResolverTag orders the results by the dns_resolver_tag field.
func ByDNSResolverTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDNSResolverTag, opts...).ToFunc()
}

// ByFallbackTarget orders the results by the fallback_target field.
func ByFallbackTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackTarget, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByEventAt orders the results by the event_at field.
func ByEventAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventAt, opts...).ToFunc()
}

// ByEventJSON orders the results by the event_json field.
func ByEventJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventJSON, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
