// Code generated by ent, DO NOT EDIT.

package proxyroutingrouteevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldID, id))
}

// ReporterType applies equality check predicate on the "reporter_type" field. It's identical to ReporterTypeEQ.
func ReporterType(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldReporterType, v))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldReporterID, v))
}

// ProfileCode applies equality check predicate on the "profile_code" field. It's identical to ProfileCodeEQ.
func ProfileCode(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldProfileCode, v))
}

// RoutingHash applies equality check predicate on the "routing_hash" field. It's identical to RoutingHashEQ.
func RoutingHash(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRoutingHash, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventType, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldSubject, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRuleID, v))
}

// RuleName applies equality check predicate on the "rule_name" field. It's identical to RuleNameEQ.
func RuleName(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRuleName, v))
}

// ActionType applies equality check predicate on the "action_type" field. It's identical to ActionTypeEQ.
func ActionType(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldActionType, v))
}

// OutboundTag applies equality check predicate on the "outbound_tag" field. It's identical to OutboundTagEQ.
func OutboundTag(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldOutboundTag, v))
}

// DNSResolverTag applies equality check predicate on the "dns_resolver_tag" field. It's identical to DNSResolverTagEQ.
func DNSResolverTag(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldDNSResolverTag, v))
}

// FallbackTarget applies equality check predicate on the "fallback_target" field. It's identical to FallbackTargetEQ.
func FallbackTarget(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldFallbackTarget, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldStatus, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldError, v))
}

// EventAt applies equality check predicate on the "event_at" field. It's identical to EventAtEQ.
func EventAt(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventAt, v))
}

// EventJSON applies equality check predicate on the "event_json" field. It's identical to EventJSONEQ.
func EventJSON(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReporterTypeEQ applies the EQ predicate on the "reporter_type" field.
func ReporterTypeEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldReporterType, v))
}

// ReporterTypeNEQ applies the NEQ predicate on the "reporter_type" field.
func ReporterTypeNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldReporterType, v))
}

// ReporterTypeIn applies the In predicate on the "reporter_type" field.
func ReporterTypeIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldReporterType, vs...))
}

// ReporterTypeNotIn applies the NotIn predicate on the "reporter_type" field.
func ReporterTypeNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldReporterType, vs...))
}

// ReporterTypeGT applies the GT predicate on the "reporter_type" field.
func ReporterTypeGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldReporterType, v))
}

// ReporterTypeGTE applies the GTE predicate on the "reporter_type" field.
func ReporterTypeGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldReporterType, v))
}

// ReporterTypeLT applies the LT predicate on the "reporter_type" field.
func ReporterTypeLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldReporterType, v))
}

// ReporterTypeLTE applies the LTE predicate on the "reporter_type" field.
func ReporterTypeLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldReporterType, v))
}

// ReporterTypeContains applies the Contains predicate on the "reporter_type" field.
func ReporterTypeContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldReporterType, v))
}

// ReporterTypeHasPrefix applies the HasPrefix predicate on the "reporter_type" field.
func ReporterTypeHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldReporterType, v))
}

// ReporterTypeHasSuffix applies the HasSuffix predicate on the "reporter_type" field.
func ReporterTypeHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldReporterType, v))
}

// ReporterTypeEqualFold applies the EqualFold predicate on the "reporter_type" field.
func ReporterTypeEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldReporterType, v))
}

// ReporterTypeContainsFold applies the ContainsFold predicate on the "reporter_type" field.
func ReporterTypeContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldReporterType, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDGT applies the GT predicate on the "reporter_id" field.
func ReporterIDGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldReporterID, v))
}

// ReporterIDGTE applies the GTE predicate on the "reporter_id" field.
func ReporterIDGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldReporterID, v))
}

// ReporterIDLT applies the LT predicate on the "reporter_id" field.
func ReporterIDLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldReporterID, v))
}

// ReporterIDLTE applies the LTE predicate on the "reporter_id" field.
func ReporterIDLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldReporterID, v))
}

// ReporterIDContains applies the Contains predicate on the "reporter_id" field.
func ReporterIDContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldReporterID, v))
}

// ReporterIDHasPrefix applies the HasPrefix predicate on the "reporter_id" field.
func ReporterIDHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldReporterID, v))
}

// ReporterIDHasSuffix applies the HasSuffix predicate on the "reporter_id" field.
func ReporterIDHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldReporterID, v))
}

// ReporterIDEqualFold applies the EqualFold predicate on the "reporter_id" field.
func ReporterIDEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldReporterID, v))
}

// ReporterIDContainsFold applies the ContainsFold predicate on the "reporter_id" field.
func ReporterIDContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldReporterID, v))
}

// ProfileCodeEQ applies the EQ predicate on the "profile_code" field.
func ProfileCodeEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldProfileCode, v))
}

// ProfileCodeNEQ applies the NEQ predicate on the "profile_code" field.
func ProfileCodeNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldProfileCode, v))
}

// ProfileCodeIn applies the In predicate on the "profile_code" field.
func ProfileCodeIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldProfileCode, vs...))
}

// ProfileCodeNotIn applies the NotIn predicate on the "profile_code" field.
func ProfileCodeNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldProfileCode, vs...))
}

// ProfileCodeGT applies the GT predicate on the "profile_code" field.
func ProfileCodeGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldProfileCode, v))
}

// ProfileCodeGTE applies the GTE predicate on the "profile_code" field.
func ProfileCodeGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldProfileCode, v))
}

// ProfileCodeLT applies the LT predicate on the "profile_code" field.
func ProfileCodeLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldProfileCode, v))
}

// ProfileCodeLTE applies the LTE predicate on the "profile_code" field.
func ProfileCodeLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldProfileCode, v))
}

// ProfileCodeContains applies the Contains predicate on the "profile_code" field.
func ProfileCodeContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldProfileCode, v))
}

// ProfileCodeHasPrefix applies the HasPrefix predicate on the "profile_code" field.
func ProfileCodeHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldProfileCode, v))
}

// ProfileCodeHasSuffix applies the HasSuffix predicate on the "profile_code" field.
func ProfileCodeHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldProfileCode, v))
}

// ProfileCodeEqualFold applies the EqualFold predicate on the "profile_code" field.
func ProfileCodeEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldProfileCode, v))
}

// ProfileCodeContainsFold applies the ContainsFold predicate on the "profile_code" field.
func ProfileCodeContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldProfileCode, v))
}

// RoutingHashEQ applies the EQ predicate on the "routing_hash" field.
func RoutingHashEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRoutingHash, v))
}

// RoutingHashNEQ applies the NEQ predicate on the "routing_hash" field.
func RoutingHashNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldRoutingHash, v))
}

// RoutingHashIn applies the In predicate on the "routing_hash" field.
func RoutingHashIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldRoutingHash, vs...))
}

// RoutingHashNotIn applies the NotIn predicate on the "routing_hash" field.
func RoutingHashNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldRoutingHash, vs...))
}

// RoutingHashGT applies the GT predicate on the "routing_hash" field.
func RoutingHashGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldRoutingHash, v))
}

// RoutingHashGTE applies the GTE predicate on the "routing_hash" field.
func RoutingHashGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldRoutingHash, v))
}

// RoutingHashLT applies the LT predicate on the "routing_hash" field.
func RoutingHashLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldRoutingHash, v))
}

// RoutingHashLTE applies the LTE predicate on the "routing_hash" field.
func RoutingHashLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldRoutingHash, v))
}

// RoutingHashContains applies the Contains predicate on the "routing_hash" field.
func RoutingHashContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldRoutingHash, v))
}

// RoutingHashHasPrefix applies the HasPrefix predicate on the "routing_hash" field.
func RoutingHashHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldRoutingHash, v))
}

// RoutingHashHasSuffix applies the HasSuffix predicate on the "routing_hash" field.
func RoutingHashHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldRoutingHash, v))
}

// RoutingHashEqualFold applies the EqualFold predicate on the "routing_hash" field.
func RoutingHashEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldRoutingHash, v))
}

// RoutingHashContainsFold applies the ContainsFold predicate on the "routing_hash" field.
func RoutingHashContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldRoutingHash, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldEventType, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldSubject, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldRuleID, v))
}

// RuleNameEQ applies the EQ predicate on the "rule_name" field.
func RuleNameEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldRuleName, v))
}

// RuleNameNEQ applies the NEQ predicate on the "rule_name" field.
func RuleNameNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldRuleName, v))
}

// RuleNameIn applies the In predicate on the "rule_name" field.
func RuleNameIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldRuleName, vs...))
}

// RuleNameNotIn applies the NotIn predicate on the "rule_name" field.
func RuleNameNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldRuleName, vs...))
}

// RuleNameGT applies the GT predicate on the "rule_name" field.
func RuleNameGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldRuleName, v))
}

// RuleNameGTE applies the GTE predicate on the "rule_name" field.
func RuleNameGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldRuleName, v))
}

// RuleNameLT applies the LT predicate on the "rule_name" field.
func RuleNameLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldRuleName, v))
}

// RuleNameLTE applies the LTE predicate on the "rule_name" field.
func RuleNameLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldRuleName, v))
}

// RuleNameContains applies the Contains predicate on the "rule_name" field.
func RuleNameContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldRuleName, v))
}

// RuleNameHasPrefix applies the HasPrefix predicate on the "rule_name" field.
func RuleNameHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldRuleName, v))
}

// RuleNameHasSuffix applies the HasSuffix predicate on the "rule_name" field.
func RuleNameHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldRuleName, v))
}

// RuleNameEqualFold applies the EqualFold predicate on the "rule_name" field.
func RuleNameEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldRuleName, v))
}

// RuleNameContainsFold applies the ContainsFold predicate on the "rule_name" field.
func RuleNameContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldRuleName, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldActionType, vs...))
}

// ActionTypeGT applies the GT predicate on the "action_type" field.
func ActionTypeGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldActionType, v))
}

// ActionTypeGTE applies the GTE predicate on the "action_type" field.
func ActionTypeGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldActionType, v))
}

// ActionTypeLT applies the LT predicate on the "action_type" field.
func ActionTypeLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldActionType, v))
}

// ActionTypeLTE applies the LTE predicate on the "action_type" field.
func ActionTypeLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldActionType, v))
}

// ActionTypeContains applies the Contains predicate on the "action_type" field.
func ActionTypeContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldActionType, v))
}

// ActionTypeHasPrefix applies the HasPrefix predicate on the "action_type" field.
func ActionTypeHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldActionType, v))
}

// ActionTypeHasSuffix applies the HasSuffix predicate on the "action_type" field.
func ActionTypeHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldActionType, v))
}

// ActionTypeEqualFold applies the EqualFold predicate on the "action_type" field.
func ActionTypeEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldActionType, v))
}

// ActionTypeContainsFold applies the ContainsFold predicate on the "action_type" field.
func ActionTypeContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldActionType, v))
}

// OutboundTagEQ applies the EQ predicate on the "outbound_tag" field.
func OutboundTagEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldOutboundTag, v))
}

// OutboundTagNEQ applies the NEQ predicate on the "outbound_tag" field.
func OutboundTagNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldOutboundTag, v))
}

// OutboundTagIn applies the In predicate on the "outbound_tag" field.
func OutboundTagIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldOutboundTag, vs...))
}

// OutboundTagNotIn applies the NotIn predicate on the "outbound_tag" field.
func OutboundTagNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldOutboundTag, vs...))
}

// OutboundTagGT applies the GT predicate on the "outbound_tag" field.
func OutboundTagGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldOutboundTag, v))
}

// OutboundTagGTE applies the GTE predicate on the "outbound_tag" field.
func OutboundTagGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldOutboundTag, v))
}

// OutboundTagLT applies the LT predicate on the "outbound_tag" field.
func OutboundTagLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldOutboundTag, v))
}

// OutboundTagLTE applies the LTE predicate on the "outbound_tag" field.
func OutboundTagLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldOutboundTag, v))
}

// OutboundTagContains applies the Contains predicate on the "outbound_tag" field.
func OutboundTagContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldOutboundTag, v))
}

// OutboundTagHasPrefix applies the HasPrefix predicate on the "outbound_tag" field.
func OutboundTagHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldOutboundTag, v))
}

// OutboundTagHasSuffix applies the HasSuffix predicate on the "outbound_tag" field.
func OutboundTagHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldOutboundTag, v))
}

// OutboundTagEqualFold applies the EqualFold predicate on the "outbound_tag" field.
func OutboundTagEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldOutboundTag, v))
}

// OutboundTagContainsFold applies the ContainsFold predicate on the "outbound_tag" field.
func OutboundTagContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldOutboundTag, v))
}

// DNSResolverTagEQ applies the EQ predicate on the "dns_resolver_tag" field.
func DNSResolverTagEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldDNSResolverTag, v))
}

// DNSResolverTagNEQ applies the NEQ predicate on the "dns_resolver_tag" field.
func DNSResolverTagNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldDNSResolverTag, v))
}

// DNSResolverTagIn applies the In predicate on the "dns_resolver_tag" field.
func DNSResolverTagIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldDNSResolverTag, vs...))
}

// DNSResolverTagNotIn applies the NotIn predicate on the "dns_resolver_tag" field.
func DNSResolverTagNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldDNSResolverTag, vs...))
}

// DNSResolverTagGT applies the GT predicate on the "dns_resolver_tag" field.
func DNSResolverTagGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldDNSResolverTag, v))
}

// DNSResolverTagGTE applies the GTE predicate on the "dns_resolver_tag" field.
func DNSResolverTagGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldDNSResolverTag, v))
}

// DNSResolverTagLT applies the LT predicate on the "dns_resolver_tag" field.
func DNSResolverTagLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldDNSResolverTag, v))
}

// DNSResolverTagLTE applies the LTE predicate on the "dns_resolver_tag" field.
func DNSResolverTagLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldDNSResolverTag, v))
}

// DNSResolverTagContains applies the Contains predicate on the "dns_resolver_tag" field.
func DNSResolverTagContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldDNSResolverTag, v))
}

// DNSResolverTagHasPrefix applies the HasPrefix predicate on the "dns_resolver_tag" field.
func DNSResolverTagHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldDNSResolverTag, v))
}

// DNSResolverTagHasSuffix applies the HasSuffix predicate on the "dns_resolver_tag" field.
func DNSResolverTagHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldDNSResolverTag, v))
}

// DNSResolverTagEqualFold applies the EqualFold predicate on the "dns_resolver_tag" field.
func DNSResolverTagEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldDNSResolverTag, v))
}

// DNSResolverTagContainsFold applies the ContainsFold predicate on the "dns_resolver_tag" field.
func DNSResolverTagContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldDNSResolverTag, v))
}

// FallbackTargetEQ applies the EQ predicate on the "fallback_target" field.
func FallbackTargetEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldFallbackTarget, v))
}

// FallbackTargetNEQ applies the NEQ predicate on the "fallback_target" field.
func FallbackTargetNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldFallbackTarget, v))
}

// FallbackTargetIn applies the In predicate on the "fallback_target" field.
func FallbackTargetIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldFallbackTarget, vs...))
}

// FallbackTargetNotIn applies the NotIn predicate on the "fallback_target" field.
func FallbackTargetNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldFallbackTarget, vs...))
}

// FallbackTargetGT applies the GT predicate on the "fallback_target" field.
func FallbackTargetGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldFallbackTarget, v))
}

// FallbackTargetGTE applies the GTE predicate on the "fallback_target" field.
func FallbackTargetGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldFallbackTarget, v))
}

// FallbackTargetLT applies the LT predicate on the "fallback_target" field.
func FallbackTargetLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldFallbackTarget, v))
}

// FallbackTargetLTE applies the LTE predicate on the "fallback_target" field.
func FallbackTargetLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldFallbackTarget, v))
}

// FallbackTargetContains applies the Contains predicate on the "fallback_target" field.
func FallbackTargetContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldFallbackTarget, v))
}

// FallbackTargetHasPrefix applies the HasPrefix predicate on the "fallback_target" field.
func FallbackTargetHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldFallbackTarget, v))
}

// FallbackTargetHasSuffix applies the HasSuffix predicate on the "fallback_target" field.
func FallbackTargetHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldFallbackTarget, v))
}

// FallbackTargetEqualFold applies the EqualFold predicate on the "fallback_target" field.
func FallbackTargetEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldFallbackTarget, v))
}

// FallbackTargetContainsFold applies the ContainsFold predicate on the "fallback_target" field.
func FallbackTargetContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldFallbackTarget, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldStatus, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldLatencyMs, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldError, v))
}

// EventAtEQ applies the EQ predicate on the "event_at" field.
func EventAtEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventAt, v))
}

// EventAtNEQ applies the NEQ predicate on the "event_at" field.
func EventAtNEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldEventAt, v))
}

// EventAtIn applies the In predicate on the "event_at" field.
func EventAtIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldEventAt, vs...))
}

// EventAtNotIn applies the NotIn predicate on the "event_at" field.
func EventAtNotIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldEventAt, vs...))
}

// EventAtGT applies the GT predicate on the "event_at" field.
func EventAtGT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldEventAt, v))
}

// EventAtGTE applies the GTE predicate on the "event_at" field.
func EventAtGTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldEventAt, v))
}

// EventAtLT applies the LT predicate on the "event_at" field.
func EventAtLT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldEventAt, v))
}

// EventAtLTE applies the LTE predicate on the "event_at" field.
func EventAtLTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldEventAt, v))
}

// EventJSONEQ applies the EQ predicate on the "event_json" field.
func EventJSONEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldEventJSON, v))
}

// EventJSONNEQ applies the NEQ predicate on the "event_json" field.
func EventJSONNEQ(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldEventJSON, v))
}

// EventJSONIn applies the In predicate on the "event_json" field.
func EventJSONIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldEventJSON, vs...))
}

// EventJSONNotIn applies the NotIn predicate on the "event_json" field.
func EventJSONNotIn(vs ...string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldEventJSON, vs...))
}

// EventJSONGT applies the GT predicate on the "event_json" field.
func EventJSONGT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldEventJSON, v))
}

// EventJSONGTE applies the GTE predicate on the "event_json" field.
func EventJSONGTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldEventJSON, v))
}

// EventJSONLT applies the LT predicate on the "event_json" field.
func EventJSONLT(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldEventJSON, v))
}

// EventJSONLTE applies the LTE predicate on the "event_json" field.
func EventJSONLTE(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldEventJSON, v))
}

// EventJSONContains applies the Contains predicate on the "event_json" field.
func EventJSONContains(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContains(FieldEventJSON, v))
}

// EventJSONHasPrefix applies the HasPrefix predicate on the "event_json" field.
func EventJSONHasPrefix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasPrefix(FieldEventJSON, v))
}

// EventJSONHasSuffix applies the HasSuffix predicate on the "event_json" field.
func EventJSONHasSuffix(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldHasSuffix(FieldEventJSON, v))
}

// EventJSONEqualFold applies the EqualFold predicate on the "event_json" field.
func EventJSONEqualFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEqualFold(FieldEventJSON, v))
}

// EventJSONContainsFold applies the ContainsFold predicate on the "event_json" field.
func EventJSONContainsFold(v string) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldContainsFold(FieldEventJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyRoutingRouteEvent) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyRoutingRouteEvent) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyRoutingRouteEvent) predicate.ProxyRoutingRouteEvent {
	return predicate.ProxyRoutingRouteEvent(sql.NotPredicates(p))
}
