CREATE TABLE IF NOT EXISTS `routing_route_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Routing route event ID',
  `reporter_type` varchar(32) NOT NULL DEFAULT 'client' COMMENT 'client/node/backend',
  `reporter_id` varchar(128) NOT NULL DEFAULT '' COMMENT 'Reporter identifier',
  `profile_code` varchar(128) NOT NULL DEFAULT '' COMMENT 'Routing profile code',
  `routing_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'Routing hash',
  `event_type` varchar(64) NOT NULL COMMENT 'route_decision/route_fallback/outbound_health_changed/dns_resolver_health_changed',
  `subject` varchar(256) NOT NULL DEFAULT '' COMMENT 'Domain, IP, service or target',
  `rule_id` varchar(128) NOT NULL DEFAULT '' COMMENT 'Matched rule ID',
  `rule_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Matched rule name',
  `action_type` varchar(32) NOT NULL DEFAULT '' COMMENT 'direct/proxy/reject/dns_resolver/outbound',
  `outbound_tag` varchar(128) NOT NULL DEFAULT '' COMMENT 'Outbound tag',
  `dns_resolver_tag` varchar(128) NOT NULL DEFAULT '' COMMENT 'DNS resolver tag',
  `fallback_target` varchar(128) NOT NULL DEFAULT '' COMMENT 'Fallback target',
  `status` varchar(32) NOT NULL DEFAULT 'unknown' COMMENT 'matched/fallback/healthy/failed/degraded/unknown',
  `latency_ms` bigint NOT NULL DEFAULT 0 COMMENT 'Latency in milliseconds',
  `error` text COMMENT 'Event error',
  `event_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Event time',
  `event_json` text NOT NULL COMMENT 'Raw route event JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
  PRIMARY KEY (`id`),
  KEY `idx_routing_route_event_profile` (`profile_code`, `routing_hash`),
  KEY `idx_routing_route_event_type_time` (`event_type`, `event_at`),
  KEY `idx_routing_route_event_reporter` (`reporter_type`, `reporter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Routing route event reports';
