CREATE TABLE IF NOT EXISTS `routing_health_report` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Routing health report ID',
    `reporter_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'client' COMMENT 'client/node/backend',
    `reporter_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Reporter identifier',
    `profile_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Routing profile code',
    `routing_hash` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Routing hash',
    `subject_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'outbound/dns_resolver/service',
    `subject_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Outbound tag, DNS resolver tag or service code',
    `region` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Region code',
    `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'unknown' COMMENT 'healthy/ok/failed/degraded/stale/disabled/unknown',
    `source` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'health_report' COMMENT 'Health source',
    `rtt_ms` bigint NOT NULL DEFAULT 0 COMMENT 'RTT in milliseconds',
    `consecutive_failures` bigint NOT NULL DEFAULT 0 COMMENT 'Consecutive failures',
    `last_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'Last health error',
    `outbound_tag` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Related outbound tag',
    `dns_resolver_tag` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Related DNS resolver tag',
    `checked_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Checked at',
    `report_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Raw health report JSON',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    PRIMARY KEY (`id`),
    KEY `routing_health_subject_idx` (`subject_type`, `subject_key`, `checked_at`),
    KEY `routing_health_profile_idx` (`profile_code`, `routing_hash`, `checked_at`),
    KEY `routing_health_reporter_idx` (`reporter_type`, `reporter_id`, `checked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
