// Code generated by ent, DO NOT EDIT.

package proxyroutinghealthreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldID, id))
}

// ReporterType applies equality check predicate on the "reporter_type" field. It's identical to ReporterTypeEQ.
func ReporterType(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReporterType, v))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReporterID, v))
}

// ProfileCode applies equality check predicate on the "profile_code" field. It's identical to ProfileCodeEQ.
func ProfileCode(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldProfileCode, v))
}

// RoutingHash applies equality check predicate on the "routing_hash" field. It's identical to RoutingHashEQ.
func RoutingHash(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRoutingHash, v))
}

// SubjectType applies equality check predicate on the "subject_type" field. It's identical to SubjectTypeEQ.
func SubjectType(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectKey applies equality check predicate on the "subject_key" field. It's identical to SubjectKeyEQ.
func SubjectKey(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSubjectKey, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRegion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSource, v))
}

// RttMs applies equality check predicate on the "rtt_ms" field. It's identical to RttMsEQ.
func RttMs(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRttMs, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldLastError, v))
}

// OutboundTag applies equality check predicate on the "outbound_tag" field. It's identical to OutboundTagEQ.
func OutboundTag(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldOutboundTag, v))
}

// DNSResolverTag applies equality check predicate on the "dns_resolver_tag" field. It's identical to DNSResolverTagEQ.
func DNSResolverTag(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldDNSResolverTag, v))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldCheckedAt, v))
}

// ReportJSON applies equality check predicate on the "report_json" field. It's identical to ReportJSONEQ.
func ReportJSON(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReportJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReporterTypeEQ applies the EQ predicate on the "reporter_type" field.
func ReporterTypeEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReporterType, v))
}

// ReporterTypeNEQ applies the NEQ predicate on the "reporter_type" field.
func ReporterTypeNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldReporterType, v))
}

// ReporterTypeIn applies the In predicate on the "reporter_type" field.
func ReporterTypeIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldReporterType, vs...))
}

// ReporterTypeNotIn applies the NotIn predicate on the "reporter_type" field.
func ReporterTypeNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldReporterType, vs...))
}

// ReporterTypeGT applies the GT predicate on the "reporter_type" field.
func ReporterTypeGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldReporterType, v))
}

// ReporterTypeGTE applies the GTE predicate on the "reporter_type" field.
func ReporterTypeGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldReporterType, v))
}

// ReporterTypeLT applies the LT predicate on the "reporter_type" field.
func ReporterTypeLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldReporterType, v))
}

// ReporterTypeLTE applies the LTE predicate on the "reporter_type" field.
func ReporterTypeLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldReporterType, v))
}

// ReporterTypeContains applies the Contains predicate on the "reporter_type" field.
func ReporterTypeContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldReporterType, v))
}

// ReporterTypeHasPrefix applies the HasPrefix predicate on the "reporter_type" field.
func ReporterTypeHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldReporterType, v))
}

// ReporterTypeHasSuffix applies the HasSuffix predicate on the "reporter_type" field.
func ReporterTypeHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldReporterType, v))
}

// ReporterTypeEqualFold applies the EqualFold predicate on the "reporter_type" field.
func ReporterTypeEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldReporterType, v))
}

// ReporterTypeContainsFold applies the ContainsFold predicate on the "reporter_type" field.
func ReporterTypeContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldReporterType, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDGT applies the GT predicate on the "reporter_id" field.
func ReporterIDGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldReporterID, v))
}

// ReporterIDGTE applies the GTE predicate on the "reporter_id" field.
func ReporterIDGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldReporterID, v))
}

// ReporterIDLT applies the LT predicate on the "reporter_id" field.
func ReporterIDLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldReporterID, v))
}

// ReporterIDLTE applies the LTE predicate on the "reporter_id" field.
func ReporterIDLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldReporterID, v))
}

// ReporterIDContains applies the Contains predicate on the "reporter_id" field.
func ReporterIDContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldReporterID, v))
}

// ReporterIDHasPrefix applies the HasPrefix predicate on the "reporter_id" field.
func ReporterIDHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldReporterID, v))
}

// ReporterIDHasSuffix applies the HasSuffix predicate on the "reporter_id" field.
func ReporterIDHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldReporterID, v))
}

// ReporterIDEqualFold applies the EqualFold predicate on the "reporter_id" field.
func ReporterIDEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldReporterID, v))
}

// ReporterIDContainsFold applies the ContainsFold predicate on the "reporter_id" field.
func ReporterIDContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldReporterID, v))
}

// ProfileCodeEQ applies the EQ predicate on the "profile_code" field.
func ProfileCodeEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldProfileCode, v))
}

// ProfileCodeNEQ applies the NEQ predicate on the "profile_code" field.
func ProfileCodeNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldProfileCode, v))
}

// ProfileCodeIn applies the In predicate on the "profile_code" field.
func ProfileCodeIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldProfileCode, vs...))
}

// ProfileCodeNotIn applies the NotIn predicate on the "profile_code" field.
func ProfileCodeNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldProfileCode, vs...))
}

// ProfileCodeGT applies the GT predicate on the "profile_code" field.
func ProfileCodeGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldProfileCode, v))
}

// ProfileCodeGTE applies the GTE predicate on the "profile_code" field.
func ProfileCodeGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldProfileCode, v))
}

// ProfileCodeLT applies the LT predicate on the "profile_code" field.
func ProfileCodeLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldProfileCode, v))
}

// ProfileCodeLTE applies the LTE predicate on the "profile_code" field.
func ProfileCodeLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldProfileCode, v))
}

// ProfileCodeContains applies the Contains predicate on the "profile_code" field.
func ProfileCodeContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldProfileCode, v))
}

// ProfileCodeHasPrefix applies the HasPrefix predicate on the "profile_code" field.
func ProfileCodeHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldProfileCode, v))
}

// ProfileCodeHasSuffix applies the HasSuffix predicate on the "profile_code" field.
func ProfileCodeHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldProfileCode, v))
}

// ProfileCodeEqualFold applies the EqualFold predicate on the "profile_code" field.
func ProfileCodeEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldProfileCode, v))
}

// ProfileCodeContainsFold applies the ContainsFold predicate on the "profile_code" field.
func ProfileCodeContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldProfileCode, v))
}

// RoutingHashEQ applies the EQ predicate on the "routing_hash" field.
func RoutingHashEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRoutingHash, v))
}

// RoutingHashNEQ applies the NEQ predicate on the "routing_hash" field.
func RoutingHashNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldRoutingHash, v))
}

// RoutingHashIn applies the In predicate on the "routing_hash" field.
func RoutingHashIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldRoutingHash, vs...))
}

// RoutingHashNotIn applies the NotIn predicate on the "routing_hash" field.
func RoutingHashNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldRoutingHash, vs...))
}

// RoutingHashGT applies the GT predicate on the "routing_hash" field.
func RoutingHashGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldRoutingHash, v))
}

// RoutingHashGTE applies the GTE predicate on the "routing_hash" field.
func RoutingHashGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldRoutingHash, v))
}

// RoutingHashLT applies the LT predicate on the "routing_hash" field.
func RoutingHashLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldRoutingHash, v))
}

// RoutingHashLTE applies the LTE predicate on the "routing_hash" field.
func RoutingHashLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldRoutingHash, v))
}

// RoutingHashContains applies the Contains predicate on the "routing_hash" field.
func RoutingHashContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldRoutingHash, v))
}

// RoutingHashHasPrefix applies the HasPrefix predicate on the "routing_hash" field.
func RoutingHashHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldRoutingHash, v))
}

// RoutingHashHasSuffix applies the HasSuffix predicate on the "routing_hash" field.
func RoutingHashHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldRoutingHash, v))
}

// RoutingHashEqualFold applies the EqualFold predicate on the "routing_hash" field.
func RoutingHashEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldRoutingHash, v))
}

// RoutingHashContainsFold applies the ContainsFold predicate on the "routing_hash" field.
func RoutingHashContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldRoutingHash, v))
}

// SubjectTypeEQ applies the EQ predicate on the "subject_type" field.
func SubjectTypeEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectTypeNEQ applies the NEQ predicate on the "subject_type" field.
func SubjectTypeNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldSubjectType, v))
}

// SubjectTypeIn applies the In predicate on the "subject_type" field.
func SubjectTypeIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldSubjectType, vs...))
}

// SubjectTypeNotIn applies the NotIn predicate on the "subject_type" field.
func SubjectTypeNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldSubjectType, vs...))
}

// SubjectTypeGT applies the GT predicate on the "subject_type" field.
func SubjectTypeGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldSubjectType, v))
}

// SubjectTypeGTE applies the GTE predicate on the "subject_type" field.
func SubjectTypeGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldSubjectType, v))
}

// SubjectTypeLT applies the LT predicate on the "subject_type" field.
func SubjectTypeLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldSubjectType, v))
}

// SubjectTypeLTE applies the LTE predicate on the "subject_type" field.
func SubjectTypeLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldSubjectType, v))
}

// SubjectTypeContains applies the Contains predicate on the "subject_type" field.
func SubjectTypeContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldSubjectType, v))
}

// SubjectTypeHasPrefix applies the HasPrefix predicate on the "subject_type" field.
func SubjectTypeHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldSubjectType, v))
}

// SubjectTypeHasSuffix applies the HasSuffix predicate on the "subject_type" field.
func SubjectTypeHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldSubjectType, v))
}

// SubjectTypeEqualFold applies the EqualFold predicate on the "subject_type" field.
func SubjectTypeEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldSubjectType, v))
}

// SubjectTypeContainsFold applies the ContainsFold predicate on the "subject_type" field.
func SubjectTypeContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldSubjectType, v))
}

// SubjectKeyEQ applies the EQ predicate on the "subject_key" field.
func SubjectKeyEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSubjectKey, v))
}

// SubjectKeyNEQ applies the NEQ predicate on the "subject_key" field.
func SubjectKeyNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldSubjectKey, v))
}

// SubjectKeyIn applies the In predicate on the "subject_key" field.
func SubjectKeyIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldSubjectKey, vs...))
}

// SubjectKeyNotIn applies the NotIn predicate on the "subject_key" field.
func SubjectKeyNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldSubjectKey, vs...))
}

// SubjectKeyGT applies the GT predicate on the "subject_key" field.
func SubjectKeyGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldSubjectKey, v))
}

// SubjectKeyGTE applies the GTE predicate on the "subject_key" field.
func SubjectKeyGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldSubjectKey, v))
}

// SubjectKeyLT applies the LT predicate on the "subject_key" field.
func SubjectKeyLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldSubjectKey, v))
}

// SubjectKeyLTE applies the LTE predicate on the "subject_key" field.
func SubjectKeyLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldSubjectKey, v))
}

// SubjectKeyContains applies the Contains predicate on the "subject_key" field.
func SubjectKeyContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldSubjectKey, v))
}

// SubjectKeyHasPrefix applies the HasPrefix predicate on the "subject_key" field.
func SubjectKeyHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldSubjectKey, v))
}

// SubjectKeyHasSuffix applies the HasSuffix predicate on the "subject_key" field.
func SubjectKeyHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldSubjectKey, v))
}

// SubjectKeyEqualFold applies the EqualFold predicate on the "subject_key" field.
func SubjectKeyEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldSubjectKey, v))
}

// SubjectKeyContainsFold applies the ContainsFold predicate on the "subject_key" field.
func SubjectKeyContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldSubjectKey, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldRegion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldSource, v))
}

// RttMsEQ applies the EQ predicate on the "rtt_ms" field.
func RttMsEQ(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldRttMs, v))
}

// RttMsNEQ applies the NEQ predicate on the "rtt_ms" field.
func RttMsNEQ(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldRttMs, v))
}

// RttMsIn applies the In predicate on the "rtt_ms" field.
func RttMsIn(vs ...int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldRttMs, vs...))
}

// RttMsNotIn applies the NotIn predicate on the "rtt_ms" field.
func RttMsNotIn(vs ...int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldRttMs, vs...))
}

// RttMsGT applies the GT predicate on the "rtt_ms" field.
func RttMsGT(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldRttMs, v))
}

// RttMsGTE applies the GTE predicate on the "rtt_ms" field.
func RttMsGTE(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldRttMs, v))
}

// RttMsLT applies the LT predicate on the "rtt_ms" field.
func RttMsLT(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldRttMs, v))
}

// RttMsLTE applies the LTE predicate on the "rtt_ms" field.
func RttMsLTE(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldRttMs, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldLastError, v))
}

// OutboundTagEQ applies the EQ predicate on the "outbound_tag" field.
func OutboundTagEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldOutboundTag, v))
}

// OutboundTagNEQ applies the NEQ predicate on the "outbound_tag" field.
func OutboundTagNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldOutboundTag, v))
}

// OutboundTagIn applies the In predicate on the "outbound_tag" field.
func OutboundTagIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldOutboundTag, vs...))
}

// OutboundTagNotIn applies the NotIn predicate on the "outbound_tag" field.
func OutboundTagNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldOutboundTag, vs...))
}

// OutboundTagGT applies the GT predicate on the "outbound_tag" field.
func OutboundTagGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldOutboundTag, v))
}

// OutboundTagGTE applies the GTE predicate on the "outbound_tag" field.
func OutboundTagGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldOutboundTag, v))
}

// OutboundTagLT applies the LT predicate on the "outbound_tag" field.
func OutboundTagLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldOutboundTag, v))
}

// OutboundTagLTE applies the LTE predicate on the "outbound_tag" field.
func OutboundTagLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldOutboundTag, v))
}

// OutboundTagContains applies the Contains predicate on the "outbound_tag" field.
func OutboundTagContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldOutboundTag, v))
}

// OutboundTagHasPrefix applies the HasPrefix predicate on the "outbound_tag" field.
func OutboundTagHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldOutboundTag, v))
}

// OutboundTagHasSuffix applies the HasSuffix predicate on the "outbound_tag" field.
func OutboundTagHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldOutboundTag, v))
}

// OutboundTagEqualFold applies the EqualFold predicate on the "outbound_tag" field.
func OutboundTagEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldOutboundTag, v))
}

// OutboundTagContainsFold applies the ContainsFold predicate on the "outbound_tag" field.
func OutboundTagContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldOutboundTag, v))
}

// DNSResolverTagEQ applies the EQ predicate on the "dns_resolver_tag" field.
func DNSResolverTagEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldDNSResolverTag, v))
}

// DNSResolverTagNEQ applies the NEQ predicate on the "dns_resolver_tag" field.
func DNSResolverTagNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldDNSResolverTag, v))
}

// DNSResolverTagIn applies the In predicate on the "dns_resolver_tag" field.
func DNSResolverTagIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldDNSResolverTag, vs...))
}

// DNSResolverTagNotIn applies the NotIn predicate on the "dns_resolver_tag" field.
func DNSResolverTagNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldDNSResolverTag, vs...))
}

// DNSResolverTagGT applies the GT predicate on the "dns_resolver_tag" field.
func DNSResolverTagGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldDNSResolverTag, v))
}

// DNSResolverTagGTE applies the GTE predicate on the "dns_resolver_tag" field.
func DNSResolverTagGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldDNSResolverTag, v))
}

// DNSResolverTagLT applies the LT predicate on the "dns_resolver_tag" field.
func DNSResolverTagLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldDNSResolverTag, v))
}

// DNSResolverTagLTE applies the LTE predicate on the "dns_resolver_tag" field.
func DNSResolverTagLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldDNSResolverTag, v))
}

// DNSResolverTagContains applies the Contains predicate on the "dns_resolver_tag" field.
func DNSResolverTagContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldDNSResolverTag, v))
}

// DNSResolverTagHasPrefix applies the HasPrefix predicate on the "dns_resolver_tag" field.
func DNSResolverTagHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldDNSResolverTag, v))
}

// DNSResolverTagHasSuffix applies the HasSuffix predicate on the "dns_resolver_tag" field.
func DNSResolverTagHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldDNSResolverTag, v))
}

// DNSResolverTagEqualFold applies the EqualFold predicate on the "dns_resolver_tag" field.
func DNSResolverTagEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldDNSResolverTag, v))
}

// DNSResolverTagContainsFold applies the ContainsFold predicate on the "dns_resolver_tag" field.
func DNSResolverTagContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldDNSResolverTag, v))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldCheckedAt, v))
}

// ReportJSONEQ applies the EQ predicate on the "report_json" field.
func ReportJSONEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldReportJSON, v))
}

// ReportJSONNEQ applies the NEQ predicate on the "report_json" field.
func ReportJSONNEQ(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldReportJSON, v))
}

// ReportJSONIn applies the In predicate on the "report_json" field.
func ReportJSONIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldReportJSON, vs...))
}

// ReportJSONNotIn applies the NotIn predicate on the "report_json" field.
func ReportJSONNotIn(vs ...string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldReportJSON, vs...))
}

// ReportJSONGT applies the GT predicate on the "report_json" field.
func ReportJSONGT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldReportJSON, v))
}

// ReportJSONGTE applies the GTE predicate on the "report_json" field.
func ReportJSONGTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldReportJSON, v))
}

// ReportJSONLT applies the LT predicate on the "report_json" field.
func ReportJSONLT(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldReportJSON, v))
}

// ReportJSONLTE applies the LTE predicate on the "report_json" field.
func ReportJSONLTE(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldReportJSON, v))
}

// ReportJSONContains applies the Contains predicate on the "report_json" field.
func ReportJSONContains(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContains(FieldReportJSON, v))
}

// ReportJSONHasPrefix applies the HasPrefix predicate on the "report_json" field.
func ReportJSONHasPrefix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasPrefix(FieldReportJSON, v))
}

// ReportJSONHasSuffix applies the HasSuffix predicate on the "report_json" field.
func ReportJSONHasSuffix(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldHasSuffix(FieldReportJSON, v))
}

// ReportJSONEqualFold applies the EqualFold predicate on the "report_json" field.
func ReportJSONEqualFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEqualFold(FieldReportJSON, v))
}

// ReportJSONContainsFold applies the ContainsFold predicate on the "report_json" field.
func ReportJSONContainsFold(v string) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldContainsFold(FieldReportJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyRoutingHealthReport) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyRoutingHealthReport) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyRoutingHealthReport) predicate.ProxyRoutingHealthReport {
	return predicate.ProxyRoutingHealthReport(sql.NotPredicates(p))
}
