// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/console/v1/console.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on QueryRevenueStatisticsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryRevenueStatisticsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryRevenueStatisticsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// QueryRevenueStatisticsRequestMultiError, or nil if none found.
func (m *QueryRevenueStatisticsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryRevenueStatisticsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryRevenueStatisticsRequestMultiError(errors)
	}

	return nil
}

// QueryRevenueStatisticsRequestMultiError is an error wrapping multiple
// validation errors returned by QueryRevenueStatisticsRequest.ValidateAll()
// if the designated constraints aren't met.
type QueryRevenueStatisticsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryRevenueStatisticsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryRevenueStatisticsRequestMultiError) AllErrors() []error { return m }

// QueryRevenueStatisticsRequestValidationError is the validation error
// returned by QueryRevenueStatisticsRequest.Validate if the designated
// constraints aren't met.
type QueryRevenueStatisticsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryRevenueStatisticsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryRevenueStatisticsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryRevenueStatisticsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryRevenueStatisticsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryRevenueStatisticsRequestValidationError) ErrorName() string {
	return "QueryRevenueStatisticsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryRevenueStatisticsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryRevenueStatisticsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryRevenueStatisticsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryRevenueStatisticsRequestValidationError{}

// Validate checks the field values on OrdersStatistics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OrdersStatistics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrdersStatistics with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrdersStatisticsMultiError, or nil if none found.
func (m *OrdersStatistics) ValidateAll() error {
	return m.validate(true)
}

func (m *OrdersStatistics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AmountTotal

	// no validation rules for NewOrderAmount

	// no validation rules for RenewalOrderAmount

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrdersStatisticsValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrdersStatisticsValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrdersStatisticsValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OrdersStatisticsMultiError(errors)
	}

	return nil
}

// OrdersStatisticsMultiError is an error wrapping multiple validation errors
// returned by OrdersStatistics.ValidateAll() if the designated constraints
// aren't met.
type OrdersStatisticsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrdersStatisticsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrdersStatisticsMultiError) AllErrors() []error { return m }

// OrdersStatisticsValidationError is the validation error returned by
// OrdersStatistics.Validate if the designated constraints aren't met.
type OrdersStatisticsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrdersStatisticsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrdersStatisticsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrdersStatisticsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrdersStatisticsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrdersStatisticsValidationError) ErrorName() string { return "OrdersStatisticsValidationError" }

// Error satisfies the builtin error interface
func (e OrdersStatisticsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrdersStatistics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrdersStatisticsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrdersStatisticsValidationError{}

// Validate checks the field values on OrdersStatisticsWithDate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrdersStatisticsWithDate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrdersStatisticsWithDate with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrdersStatisticsWithDateMultiError, or nil if none found.
func (m *OrdersStatisticsWithDate) ValidateAll() error {
	return m.validate(true)
}

func (m *OrdersStatisticsWithDate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Date

	// no validation rules for AmountTotal

	// no validation rules for NewOrderAmount

	// no validation rules for RenewalOrderAmount

	if len(errors) > 0 {
		return OrdersStatisticsWithDateMultiError(errors)
	}

	return nil
}

// OrdersStatisticsWithDateMultiError is an error wrapping multiple validation
// errors returned by OrdersStatisticsWithDate.ValidateAll() if the designated
// constraints aren't met.
type OrdersStatisticsWithDateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrdersStatisticsWithDateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrdersStatisticsWithDateMultiError) AllErrors() []error { return m }

// OrdersStatisticsWithDateValidationError is the validation error returned by
// OrdersStatisticsWithDate.Validate if the designated constraints aren't met.
type OrdersStatisticsWithDateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrdersStatisticsWithDateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrdersStatisticsWithDateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrdersStatisticsWithDateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrdersStatisticsWithDateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrdersStatisticsWithDateValidationError) ErrorName() string {
	return "OrdersStatisticsWithDateValidationError"
}

// Error satisfies the builtin error interface
func (e OrdersStatisticsWithDateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrdersStatisticsWithDate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrdersStatisticsWithDateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrdersStatisticsWithDateValidationError{}

// Validate checks the field values on QueryRevenueStatisticsData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryRevenueStatisticsData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryRevenueStatisticsData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryRevenueStatisticsDataMultiError, or nil if none found.
func (m *QueryRevenueStatisticsData) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryRevenueStatisticsData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetToday()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "Today",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "Today",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToday()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryRevenueStatisticsDataValidationError{
				field:  "Today",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMonthly()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "Monthly",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "Monthly",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMonthly()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryRevenueStatisticsDataValidationError{
				field:  "Monthly",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAll()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "All",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryRevenueStatisticsDataValidationError{
					field:  "All",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAll()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryRevenueStatisticsDataValidationError{
				field:  "All",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryRevenueStatisticsDataMultiError(errors)
	}

	return nil
}

// QueryRevenueStatisticsDataMultiError is an error wrapping multiple
// validation errors returned by QueryRevenueStatisticsData.ValidateAll() if
// the designated constraints aren't met.
type QueryRevenueStatisticsDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryRevenueStatisticsDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryRevenueStatisticsDataMultiError) AllErrors() []error { return m }

// QueryRevenueStatisticsDataValidationError is the validation error returned
// by QueryRevenueStatisticsData.Validate if the designated constraints aren't met.
type QueryRevenueStatisticsDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryRevenueStatisticsDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryRevenueStatisticsDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryRevenueStatisticsDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryRevenueStatisticsDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryRevenueStatisticsDataValidationError) ErrorName() string {
	return "QueryRevenueStatisticsDataValidationError"
}

// Error satisfies the builtin error interface
func (e QueryRevenueStatisticsDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryRevenueStatisticsData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryRevenueStatisticsDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryRevenueStatisticsDataValidationError{}

// Validate checks the field values on QueryRevenueStatisticsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryRevenueStatisticsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryRevenueStatisticsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryRevenueStatisticsReplyMultiError, or nil if none found.
func (m *QueryRevenueStatisticsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryRevenueStatisticsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryRevenueStatisticsReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryRevenueStatisticsReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryRevenueStatisticsReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryRevenueStatisticsReplyMultiError(errors)
	}

	return nil
}

// QueryRevenueStatisticsReplyMultiError is an error wrapping multiple
// validation errors returned by QueryRevenueStatisticsReply.ValidateAll() if
// the designated constraints aren't met.
type QueryRevenueStatisticsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryRevenueStatisticsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryRevenueStatisticsReplyMultiError) AllErrors() []error { return m }

// QueryRevenueStatisticsReplyValidationError is the validation error returned
// by QueryRevenueStatisticsReply.Validate if the designated constraints
// aren't met.
type QueryRevenueStatisticsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryRevenueStatisticsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryRevenueStatisticsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryRevenueStatisticsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryRevenueStatisticsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryRevenueStatisticsReplyValidationError) ErrorName() string {
	return "QueryRevenueStatisticsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryRevenueStatisticsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryRevenueStatisticsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryRevenueStatisticsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryRevenueStatisticsReplyValidationError{}

// Validate checks the field values on QueryUserStatisticsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryUserStatisticsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryUserStatisticsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryUserStatisticsRequestMultiError, or nil if none found.
func (m *QueryUserStatisticsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryUserStatisticsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryUserStatisticsRequestMultiError(errors)
	}

	return nil
}

// QueryUserStatisticsRequestMultiError is an error wrapping multiple
// validation errors returned by QueryUserStatisticsRequest.ValidateAll() if
// the designated constraints aren't met.
type QueryUserStatisticsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryUserStatisticsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryUserStatisticsRequestMultiError) AllErrors() []error { return m }

// QueryUserStatisticsRequestValidationError is the validation error returned
// by QueryUserStatisticsRequest.Validate if the designated constraints aren't met.
type QueryUserStatisticsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryUserStatisticsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryUserStatisticsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryUserStatisticsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryUserStatisticsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryUserStatisticsRequestValidationError) ErrorName() string {
	return "QueryUserStatisticsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryUserStatisticsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryUserStatisticsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryUserStatisticsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryUserStatisticsRequestValidationError{}

// Validate checks the field values on UserStatistics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserStatistics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserStatistics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserStatisticsMultiError,
// or nil if none found.
func (m *UserStatistics) ValidateAll() error {
	return m.validate(true)
}

func (m *UserStatistics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Date

	// no validation rules for Register

	// no validation rules for NewOrderUsers

	// no validation rules for RenewalOrderUsers

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserStatisticsValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserStatisticsValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserStatisticsValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserStatisticsMultiError(errors)
	}

	return nil
}

// UserStatisticsMultiError is an error wrapping multiple validation errors
// returned by UserStatistics.ValidateAll() if the designated constraints
// aren't met.
type UserStatisticsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserStatisticsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserStatisticsMultiError) AllErrors() []error { return m }

// UserStatisticsValidationError is the validation error returned by
// UserStatistics.Validate if the designated constraints aren't met.
type UserStatisticsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserStatisticsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserStatisticsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserStatisticsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserStatisticsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserStatisticsValidationError) ErrorName() string { return "UserStatisticsValidationError" }

// Error satisfies the builtin error interface
func (e UserStatisticsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserStatistics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserStatisticsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserStatisticsValidationError{}

// Validate checks the field values on QueryUserStatisticsData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryUserStatisticsData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryUserStatisticsData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryUserStatisticsDataMultiError, or nil if none found.
func (m *QueryUserStatisticsData) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryUserStatisticsData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetToday()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "Today",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "Today",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToday()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryUserStatisticsDataValidationError{
				field:  "Today",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMonthly()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "Monthly",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "Monthly",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMonthly()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryUserStatisticsDataValidationError{
				field:  "Monthly",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAll()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "All",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryUserStatisticsDataValidationError{
					field:  "All",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAll()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryUserStatisticsDataValidationError{
				field:  "All",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryUserStatisticsDataMultiError(errors)
	}

	return nil
}

// QueryUserStatisticsDataMultiError is an error wrapping multiple validation
// errors returned by QueryUserStatisticsData.ValidateAll() if the designated
// constraints aren't met.
type QueryUserStatisticsDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryUserStatisticsDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryUserStatisticsDataMultiError) AllErrors() []error { return m }

// QueryUserStatisticsDataValidationError is the validation error returned by
// QueryUserStatisticsData.Validate if the designated constraints aren't met.
type QueryUserStatisticsDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryUserStatisticsDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryUserStatisticsDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryUserStatisticsDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryUserStatisticsDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryUserStatisticsDataValidationError) ErrorName() string {
	return "QueryUserStatisticsDataValidationError"
}

// Error satisfies the builtin error interface
func (e QueryUserStatisticsDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryUserStatisticsData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryUserStatisticsDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryUserStatisticsDataValidationError{}

// Validate checks the field values on QueryUserStatisticsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryUserStatisticsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryUserStatisticsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryUserStatisticsReplyMultiError, or nil if none found.
func (m *QueryUserStatisticsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryUserStatisticsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryUserStatisticsReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryUserStatisticsReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryUserStatisticsReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryUserStatisticsReplyMultiError(errors)
	}

	return nil
}

// QueryUserStatisticsReplyMultiError is an error wrapping multiple validation
// errors returned by QueryUserStatisticsReply.ValidateAll() if the designated
// constraints aren't met.
type QueryUserStatisticsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryUserStatisticsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryUserStatisticsReplyMultiError) AllErrors() []error { return m }

// QueryUserStatisticsReplyValidationError is the validation error returned by
// QueryUserStatisticsReply.Validate if the designated constraints aren't met.
type QueryUserStatisticsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryUserStatisticsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryUserStatisticsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryUserStatisticsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryUserStatisticsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryUserStatisticsReplyValidationError) ErrorName() string {
	return "QueryUserStatisticsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryUserStatisticsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryUserStatisticsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryUserStatisticsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryUserStatisticsReplyValidationError{}

// Validate checks the field values on QueryTicketWaitReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryTicketWaitReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryTicketWaitReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryTicketWaitReplyRequestMultiError, or nil if none found.
func (m *QueryTicketWaitReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryTicketWaitReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryTicketWaitReplyRequestMultiError(errors)
	}

	return nil
}

// QueryTicketWaitReplyRequestMultiError is an error wrapping multiple
// validation errors returned by QueryTicketWaitReplyRequest.ValidateAll() if
// the designated constraints aren't met.
type QueryTicketWaitReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryTicketWaitReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryTicketWaitReplyRequestMultiError) AllErrors() []error { return m }

// QueryTicketWaitReplyRequestValidationError is the validation error returned
// by QueryTicketWaitReplyRequest.Validate if the designated constraints
// aren't met.
type QueryTicketWaitReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryTicketWaitReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryTicketWaitReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryTicketWaitReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryTicketWaitReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryTicketWaitReplyRequestValidationError) ErrorName() string {
	return "QueryTicketWaitReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryTicketWaitReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryTicketWaitReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryTicketWaitReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryTicketWaitReplyRequestValidationError{}

// Validate checks the field values on QueryTicketWaitReplyData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryTicketWaitReplyData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryTicketWaitReplyData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryTicketWaitReplyDataMultiError, or nil if none found.
func (m *QueryTicketWaitReplyData) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryTicketWaitReplyData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return QueryTicketWaitReplyDataMultiError(errors)
	}

	return nil
}

// QueryTicketWaitReplyDataMultiError is an error wrapping multiple validation
// errors returned by QueryTicketWaitReplyData.ValidateAll() if the designated
// constraints aren't met.
type QueryTicketWaitReplyDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryTicketWaitReplyDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryTicketWaitReplyDataMultiError) AllErrors() []error { return m }

// QueryTicketWaitReplyDataValidationError is the validation error returned by
// QueryTicketWaitReplyData.Validate if the designated constraints aren't met.
type QueryTicketWaitReplyDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryTicketWaitReplyDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryTicketWaitReplyDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryTicketWaitReplyDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryTicketWaitReplyDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryTicketWaitReplyDataValidationError) ErrorName() string {
	return "QueryTicketWaitReplyDataValidationError"
}

// Error satisfies the builtin error interface
func (e QueryTicketWaitReplyDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryTicketWaitReplyData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryTicketWaitReplyDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryTicketWaitReplyDataValidationError{}

// Validate checks the field values on QueryTicketWaitReplyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryTicketWaitReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryTicketWaitReplyReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryTicketWaitReplyReplyMultiError, or nil if none found.
func (m *QueryTicketWaitReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryTicketWaitReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryTicketWaitReplyReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryTicketWaitReplyReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryTicketWaitReplyReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryTicketWaitReplyReplyMultiError(errors)
	}

	return nil
}

// QueryTicketWaitReplyReplyMultiError is an error wrapping multiple validation
// errors returned by QueryTicketWaitReplyReply.ValidateAll() if the
// designated constraints aren't met.
type QueryTicketWaitReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryTicketWaitReplyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryTicketWaitReplyReplyMultiError) AllErrors() []error { return m }

// QueryTicketWaitReplyReplyValidationError is the validation error returned by
// QueryTicketWaitReplyReply.Validate if the designated constraints aren't met.
type QueryTicketWaitReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryTicketWaitReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryTicketWaitReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryTicketWaitReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryTicketWaitReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryTicketWaitReplyReplyValidationError) ErrorName() string {
	return "QueryTicketWaitReplyReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryTicketWaitReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryTicketWaitReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryTicketWaitReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryTicketWaitReplyReplyValidationError{}

// Validate checks the field values on QueryServerTotalDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryServerTotalDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryServerTotalDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryServerTotalDataRequestMultiError, or nil if none found.
func (m *QueryServerTotalDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryServerTotalDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryServerTotalDataRequestMultiError(errors)
	}

	return nil
}

// QueryServerTotalDataRequestMultiError is an error wrapping multiple
// validation errors returned by QueryServerTotalDataRequest.ValidateAll() if
// the designated constraints aren't met.
type QueryServerTotalDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryServerTotalDataRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryServerTotalDataRequestMultiError) AllErrors() []error { return m }

// QueryServerTotalDataRequestValidationError is the validation error returned
// by QueryServerTotalDataRequest.Validate if the designated constraints
// aren't met.
type QueryServerTotalDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryServerTotalDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryServerTotalDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryServerTotalDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryServerTotalDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryServerTotalDataRequestValidationError) ErrorName() string {
	return "QueryServerTotalDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryServerTotalDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryServerTotalDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryServerTotalDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryServerTotalDataRequestValidationError{}

// Validate checks the field values on ServerTrafficData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ServerTrafficData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServerTrafficData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServerTrafficDataMultiError, or nil if none found.
func (m *ServerTrafficData) ValidateAll() error {
	return m.validate(true)
}

func (m *ServerTrafficData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServerId

	// no validation rules for Name

	// no validation rules for Upload

	// no validation rules for Download

	if len(errors) > 0 {
		return ServerTrafficDataMultiError(errors)
	}

	return nil
}

// ServerTrafficDataMultiError is an error wrapping multiple validation errors
// returned by ServerTrafficData.ValidateAll() if the designated constraints
// aren't met.
type ServerTrafficDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServerTrafficDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServerTrafficDataMultiError) AllErrors() []error { return m }

// ServerTrafficDataValidationError is the validation error returned by
// ServerTrafficData.Validate if the designated constraints aren't met.
type ServerTrafficDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerTrafficDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerTrafficDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerTrafficDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerTrafficDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerTrafficDataValidationError) ErrorName() string {
	return "ServerTrafficDataValidationError"
}

// Error satisfies the builtin error interface
func (e ServerTrafficDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerTrafficData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerTrafficDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerTrafficDataValidationError{}

// Validate checks the field values on UserTrafficData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserTrafficData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserTrafficData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserTrafficDataMultiError, or nil if none found.
func (m *UserTrafficData) ValidateAll() error {
	return m.validate(true)
}

func (m *UserTrafficData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sid

	// no validation rules for Upload

	// no validation rules for Download

	if len(errors) > 0 {
		return UserTrafficDataMultiError(errors)
	}

	return nil
}

// UserTrafficDataMultiError is an error wrapping multiple validation errors
// returned by UserTrafficData.ValidateAll() if the designated constraints
// aren't met.
type UserTrafficDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserTrafficDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserTrafficDataMultiError) AllErrors() []error { return m }

// UserTrafficDataValidationError is the validation error returned by
// UserTrafficData.Validate if the designated constraints aren't met.
type UserTrafficDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserTrafficDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserTrafficDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserTrafficDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserTrafficDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserTrafficDataValidationError) ErrorName() string { return "UserTrafficDataValidationError" }

// Error satisfies the builtin error interface
func (e UserTrafficDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserTrafficData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserTrafficDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserTrafficDataValidationError{}

// Validate checks the field values on QueryServerTotalDataData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryServerTotalDataData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryServerTotalDataData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryServerTotalDataDataMultiError, or nil if none found.
func (m *QueryServerTotalDataData) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryServerTotalDataData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OnlineUsers

	// no validation rules for OnlineServers

	// no validation rules for OfflineServers

	// no validation rules for TodayUpload

	// no validation rules for TodayDownload

	// no validation rules for MonthlyUpload

	// no validation rules for MonthlyDownload

	// no validation rules for UpdatedAt

	for idx, item := range m.GetServerTrafficRankingToday() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("ServerTrafficRankingToday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("ServerTrafficRankingToday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryServerTotalDataDataValidationError{
					field:  fmt.Sprintf("ServerTrafficRankingToday[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetServerTrafficRankingYesterday() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("ServerTrafficRankingYesterday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("ServerTrafficRankingYesterday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryServerTotalDataDataValidationError{
					field:  fmt.Sprintf("ServerTrafficRankingYesterday[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetUserTrafficRankingToday() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("UserTrafficRankingToday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("UserTrafficRankingToday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryServerTotalDataDataValidationError{
					field:  fmt.Sprintf("UserTrafficRankingToday[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetUserTrafficRankingYesterday() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("UserTrafficRankingYesterday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryServerTotalDataDataValidationError{
						field:  fmt.Sprintf("UserTrafficRankingYesterday[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryServerTotalDataDataValidationError{
					field:  fmt.Sprintf("UserTrafficRankingYesterday[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueryServerTotalDataDataMultiError(errors)
	}

	return nil
}

// QueryServerTotalDataDataMultiError is an error wrapping multiple validation
// errors returned by QueryServerTotalDataData.ValidateAll() if the designated
// constraints aren't met.
type QueryServerTotalDataDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryServerTotalDataDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryServerTotalDataDataMultiError) AllErrors() []error { return m }

// QueryServerTotalDataDataValidationError is the validation error returned by
// QueryServerTotalDataData.Validate if the designated constraints aren't met.
type QueryServerTotalDataDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryServerTotalDataDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryServerTotalDataDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryServerTotalDataDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryServerTotalDataDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryServerTotalDataDataValidationError) ErrorName() string {
	return "QueryServerTotalDataDataValidationError"
}

// Error satisfies the builtin error interface
func (e QueryServerTotalDataDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryServerTotalDataData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryServerTotalDataDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryServerTotalDataDataValidationError{}

// Validate checks the field values on QueryServerTotalDataReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryServerTotalDataReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryServerTotalDataReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryServerTotalDataReplyMultiError, or nil if none found.
func (m *QueryServerTotalDataReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryServerTotalDataReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryServerTotalDataReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryServerTotalDataReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryServerTotalDataReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryServerTotalDataReplyMultiError(errors)
	}

	return nil
}

// QueryServerTotalDataReplyMultiError is an error wrapping multiple validation
// errors returned by QueryServerTotalDataReply.ValidateAll() if the
// designated constraints aren't met.
type QueryServerTotalDataReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryServerTotalDataReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryServerTotalDataReplyMultiError) AllErrors() []error { return m }

// QueryServerTotalDataReplyValidationError is the validation error returned by
// QueryServerTotalDataReply.Validate if the designated constraints aren't met.
type QueryServerTotalDataReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryServerTotalDataReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryServerTotalDataReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryServerTotalDataReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryServerTotalDataReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryServerTotalDataReplyValidationError) ErrorName() string {
	return "QueryServerTotalDataReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryServerTotalDataReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryServerTotalDataReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryServerTotalDataReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryServerTotalDataReplyValidationError{}
