// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: public/payment/v1/payment.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PaymentMethodsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PaymentMethodsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentMethodsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentMethodsReplyMultiError, or nil if none found.
func (m *PaymentMethodsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentMethodsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentMethodsReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentMethodsReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentMethodsReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PaymentMethodsReplyMultiError(errors)
	}

	return nil
}

// PaymentMethodsReplyMultiError is an error wrapping multiple validation
// errors returned by PaymentMethodsReply.ValidateAll() if the designated
// constraints aren't met.
type PaymentMethodsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentMethodsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentMethodsReplyMultiError) AllErrors() []error { return m }

// PaymentMethodsReplyValidationError is the validation error returned by
// PaymentMethodsReply.Validate if the designated constraints aren't met.
type PaymentMethodsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentMethodsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentMethodsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentMethodsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentMethodsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentMethodsReplyValidationError) ErrorName() string {
	return "PaymentMethodsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentMethodsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentMethodsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentMethodsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentMethodsReplyValidationError{}

// Validate checks the field values on PaymentMethod with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentMethod with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentMethodMultiError, or
// nil if none found.
func (m *PaymentMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Platform

	// no validation rules for Description

	// no validation rules for Icon

	// no validation rules for FeeMode

	// no validation rules for FeePercent

	// no validation rules for FeeAmount

	if len(errors) > 0 {
		return PaymentMethodMultiError(errors)
	}

	return nil
}

// PaymentMethodMultiError is an error wrapping multiple validation errors
// returned by PaymentMethod.ValidateAll() if the designated constraints
// aren't met.
type PaymentMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentMethodMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentMethodMultiError) AllErrors() []error { return m }

// PaymentMethodValidationError is the validation error returned by
// PaymentMethod.Validate if the designated constraints aren't met.
type PaymentMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentMethodValidationError) ErrorName() string { return "PaymentMethodValidationError" }

// Error satisfies the builtin error interface
func (e PaymentMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentMethodValidationError{}

// Validate checks the field values on AlipayNotifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AlipayNotifyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AlipayNotifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AlipayNotifyRequestMultiError, or nil if none found.
func (m *AlipayNotifyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AlipayNotifyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for TradeNo

	// no validation rules for OutTradeNo

	// no validation rules for TradeStatus

	// no validation rules for TotalAmount

	// no validation rules for ReceiptAmount

	// no validation rules for BuyerPayAmount

	// no validation rules for Subject

	// no validation rules for Body

	// no validation rules for GmtCreate

	// no validation rules for GmtPayment

	// no validation rules for NotifyTime

	// no validation rules for AppId

	// no validation rules for SellerId

	// no validation rules for SellerEmail

	// no validation rules for NotifyType

	// no validation rules for AuthAppId

	// no validation rules for Charset

	// no validation rules for Version

	// no validation rules for Sign

	// no validation rules for ExtraParams

	if len(errors) > 0 {
		return AlipayNotifyRequestMultiError(errors)
	}

	return nil
}

// AlipayNotifyRequestMultiError is an error wrapping multiple validation
// errors returned by AlipayNotifyRequest.ValidateAll() if the designated
// constraints aren't met.
type AlipayNotifyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AlipayNotifyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AlipayNotifyRequestMultiError) AllErrors() []error { return m }

// AlipayNotifyRequestValidationError is the validation error returned by
// AlipayNotifyRequest.Validate if the designated constraints aren't met.
type AlipayNotifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlipayNotifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlipayNotifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlipayNotifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlipayNotifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlipayNotifyRequestValidationError) ErrorName() string {
	return "AlipayNotifyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AlipayNotifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlipayNotifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlipayNotifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlipayNotifyRequestValidationError{}

// Validate checks the field values on AlipayNotifyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AlipayNotifyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AlipayNotifyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AlipayNotifyReplyMultiError, or nil if none found.
func (m *AlipayNotifyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AlipayNotifyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Response

	if len(errors) > 0 {
		return AlipayNotifyReplyMultiError(errors)
	}

	return nil
}

// AlipayNotifyReplyMultiError is an error wrapping multiple validation errors
// returned by AlipayNotifyReply.ValidateAll() if the designated constraints
// aren't met.
type AlipayNotifyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AlipayNotifyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AlipayNotifyReplyMultiError) AllErrors() []error { return m }

// AlipayNotifyReplyValidationError is the validation error returned by
// AlipayNotifyReply.Validate if the designated constraints aren't met.
type AlipayNotifyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlipayNotifyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlipayNotifyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlipayNotifyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlipayNotifyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlipayNotifyReplyValidationError) ErrorName() string {
	return "AlipayNotifyReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AlipayNotifyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlipayNotifyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlipayNotifyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlipayNotifyReplyValidationError{}

// Validate checks the field values on EPayNotifyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EPayNotifyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EPayNotifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EPayNotifyRequestMultiError, or nil if none found.
func (m *EPayNotifyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EPayNotifyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for Pid

	// no validation rules for TradeNo

	// no validation rules for OutTradeNo

	// no validation rules for Type

	// no validation rules for Name

	// no validation rules for Money

	// no validation rules for TradeStatus

	// no validation rules for Param

	// no validation rules for Sign

	// no validation rules for ExtraParams

	if len(errors) > 0 {
		return EPayNotifyRequestMultiError(errors)
	}

	return nil
}

// EPayNotifyRequestMultiError is an error wrapping multiple validation errors
// returned by EPayNotifyRequest.ValidateAll() if the designated constraints
// aren't met.
type EPayNotifyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EPayNotifyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EPayNotifyRequestMultiError) AllErrors() []error { return m }

// EPayNotifyRequestValidationError is the validation error returned by
// EPayNotifyRequest.Validate if the designated constraints aren't met.
type EPayNotifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EPayNotifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EPayNotifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EPayNotifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EPayNotifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EPayNotifyRequestValidationError) ErrorName() string {
	return "EPayNotifyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EPayNotifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEPayNotifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EPayNotifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EPayNotifyRequestValidationError{}

// Validate checks the field values on EPayNotifyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EPayNotifyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EPayNotifyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EPayNotifyReplyMultiError, or nil if none found.
func (m *EPayNotifyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *EPayNotifyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Response

	if len(errors) > 0 {
		return EPayNotifyReplyMultiError(errors)
	}

	return nil
}

// EPayNotifyReplyMultiError is an error wrapping multiple validation errors
// returned by EPayNotifyReply.ValidateAll() if the designated constraints
// aren't met.
type EPayNotifyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EPayNotifyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EPayNotifyReplyMultiError) AllErrors() []error { return m }

// EPayNotifyReplyValidationError is the validation error returned by
// EPayNotifyReply.Validate if the designated constraints aren't met.
type EPayNotifyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EPayNotifyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EPayNotifyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EPayNotifyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EPayNotifyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EPayNotifyReplyValidationError) ErrorName() string { return "EPayNotifyReplyValidationError" }

// Error satisfies the builtin error interface
func (e EPayNotifyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEPayNotifyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EPayNotifyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EPayNotifyReplyValidationError{}

// Validate checks the field values on StripeNotifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StripeNotifyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StripeNotifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StripeNotifyRequestMultiError, or nil if none found.
func (m *StripeNotifyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StripeNotifyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for Payload

	// no validation rules for StripeSignature

	if len(errors) > 0 {
		return StripeNotifyRequestMultiError(errors)
	}

	return nil
}

// StripeNotifyRequestMultiError is an error wrapping multiple validation
// errors returned by StripeNotifyRequest.ValidateAll() if the designated
// constraints aren't met.
type StripeNotifyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StripeNotifyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StripeNotifyRequestMultiError) AllErrors() []error { return m }

// StripeNotifyRequestValidationError is the validation error returned by
// StripeNotifyRequest.Validate if the designated constraints aren't met.
type StripeNotifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StripeNotifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StripeNotifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StripeNotifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StripeNotifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StripeNotifyRequestValidationError) ErrorName() string {
	return "StripeNotifyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StripeNotifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStripeNotifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StripeNotifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StripeNotifyRequestValidationError{}

// Validate checks the field values on StripeNotifyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StripeNotifyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StripeNotifyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StripeNotifyReplyMultiError, or nil if none found.
func (m *StripeNotifyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *StripeNotifyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return StripeNotifyReplyMultiError(errors)
	}

	return nil
}

// StripeNotifyReplyMultiError is an error wrapping multiple validation errors
// returned by StripeNotifyReply.ValidateAll() if the designated constraints
// aren't met.
type StripeNotifyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StripeNotifyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StripeNotifyReplyMultiError) AllErrors() []error { return m }

// StripeNotifyReplyValidationError is the validation error returned by
// StripeNotifyReply.Validate if the designated constraints aren't met.
type StripeNotifyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StripeNotifyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StripeNotifyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StripeNotifyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StripeNotifyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StripeNotifyReplyValidationError) ErrorName() string {
	return "StripeNotifyReplyValidationError"
}

// Error satisfies the builtin error interface
func (e StripeNotifyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStripeNotifyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StripeNotifyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StripeNotifyReplyValidationError{}
