// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: admin/withdrawal/v1/withdrawal.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWithdrawalServiceApproveWithdrawal = "/api.admin.withdrawal.v1.WithdrawalService/ApproveWithdrawal"
const OperationWithdrawalServiceGetWithdrawalList = "/api.admin.withdrawal.v1.WithdrawalService/GetWithdrawalList"
const OperationWithdrawalServiceRejectWithdrawal = "/api.admin.withdrawal.v1.WithdrawalService/RejectWithdrawal"

type WithdrawalServiceHTTPServer interface {
	ApproveWithdrawal(context.Context, *ApproveWithdrawalRequest) (*ApproveWithdrawalReply, error)
	GetWithdrawalList(context.Context, *GetWithdrawalListRequest) (*GetWithdrawalListReply, error)
	RejectWithdrawal(context.Context, *RejectWithdrawalRequest) (*RejectWithdrawalReply, error)
}

func RegisterWithdrawalServiceHTTPServer(s *http.Server, srv WithdrawalServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/admin/withdrawal/list", _WithdrawalService_GetWithdrawalList0_HTTP_Handler(srv))
	r.POST("/v1/admin/withdrawal/approve", _WithdrawalService_ApproveWithdrawal0_HTTP_Handler(srv))
	r.POST("/v1/admin/withdrawal/reject", _WithdrawalService_RejectWithdrawal0_HTTP_Handler(srv))
}

func _WithdrawalService_GetWithdrawalList0_HTTP_Handler(srv WithdrawalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWithdrawalListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWithdrawalServiceGetWithdrawalList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWithdrawalList(ctx, req.(*GetWithdrawalListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWithdrawalListReply)
		return ctx.Result(200, reply)
	}
}

func _WithdrawalService_ApproveWithdrawal0_HTTP_Handler(srv WithdrawalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApproveWithdrawalRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWithdrawalServiceApproveWithdrawal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApproveWithdrawal(ctx, req.(*ApproveWithdrawalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApproveWithdrawalReply)
		return ctx.Result(200, reply)
	}
}

func _WithdrawalService_RejectWithdrawal0_HTTP_Handler(srv WithdrawalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RejectWithdrawalRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWithdrawalServiceRejectWithdrawal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RejectWithdrawal(ctx, req.(*RejectWithdrawalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RejectWithdrawalReply)
		return ctx.Result(200, reply)
	}
}

type WithdrawalServiceHTTPClient interface {
	ApproveWithdrawal(ctx context.Context, req *ApproveWithdrawalRequest, opts ...http.CallOption) (rsp *ApproveWithdrawalReply, err error)
	GetWithdrawalList(ctx context.Context, req *GetWithdrawalListRequest, opts ...http.CallOption) (rsp *GetWithdrawalListReply, err error)
	RejectWithdrawal(ctx context.Context, req *RejectWithdrawalRequest, opts ...http.CallOption) (rsp *RejectWithdrawalReply, err error)
}

type WithdrawalServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWithdrawalServiceHTTPClient(client *http.Client) WithdrawalServiceHTTPClient {
	return &WithdrawalServiceHTTPClientImpl{client}
}

func (c *WithdrawalServiceHTTPClientImpl) ApproveWithdrawal(ctx context.Context, in *ApproveWithdrawalRequest, opts ...http.CallOption) (*ApproveWithdrawalReply, error) {
	var out ApproveWithdrawalReply
	pattern := "/v1/admin/withdrawal/approve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWithdrawalServiceApproveWithdrawal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WithdrawalServiceHTTPClientImpl) GetWithdrawalList(ctx context.Context, in *GetWithdrawalListRequest, opts ...http.CallOption) (*GetWithdrawalListReply, error) {
	var out GetWithdrawalListReply
	pattern := "/v1/admin/withdrawal/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWithdrawalServiceGetWithdrawalList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WithdrawalServiceHTTPClientImpl) RejectWithdrawal(ctx context.Context, in *RejectWithdrawalRequest, opts ...http.CallOption) (*RejectWithdrawalReply, error) {
	var out RejectWithdrawalReply
	pattern := "/v1/admin/withdrawal/reject"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWithdrawalServiceRejectWithdrawal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
