// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutinghealthreport"
)

// ProxyRoutingHealthReportUpdate is the builder for updating ProxyRoutingHealthReport entities.
type ProxyRoutingHealthReportUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyRoutingHealthReportMutation
}

// Where appends a list predicates to the ProxyRoutingHealthReportUpdate builder.
func (_u *ProxyRoutingHealthReportUpdate) Where(ps ...predicate.ProxyRoutingHealthReport) *ProxyRoutingHealthReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReporterType sets the "reporter_type" field.
func (_u *ProxyRoutingHealthReportUpdate) SetReporterType(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetReporterType(v)
	return _u
}

// SetNillableReporterType sets the "reporter_type" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableReporterType(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetReporterType(*v)
	}
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ProxyRoutingHealthReportUpdate) SetReporterID(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableReporterID(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// SetProfileCode sets the "profile_code" field.
func (_u *ProxyRoutingHealthReportUpdate) SetProfileCode(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetProfileCode(v)
	return _u
}

// SetNillableProfileCode sets the "profile_code" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableProfileCode(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetProfileCode(*v)
	}
	return _u
}

// SetRoutingHash sets the "routing_hash" field.
func (_u *ProxyRoutingHealthReportUpdate) SetRoutingHash(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetRoutingHash(v)
	return _u
}

// SetNillableRoutingHash sets the "routing_hash" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableRoutingHash(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetRoutingHash(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *ProxyRoutingHealthReportUpdate) SetSubjectType(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableSubjectType(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectKey sets the "subject_key" field.
func (_u *ProxyRoutingHealthReportUpdate) SetSubjectKey(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetSubjectKey(v)
	return _u
}

// SetNillableSubjectKey sets the "subject_key" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableSubjectKey(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetSubjectKey(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyRoutingHealthReportUpdate) SetRegion(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableRegion(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyRoutingHealthReportUpdate) SetStatus(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableStatus(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ProxyRoutingHealthReportUpdate) SetSource(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableSource(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRttMs sets the "rtt_ms" field.
func (_u *ProxyRoutingHealthReportUpdate) SetRttMs(v int) *ProxyRoutingHealthReportUpdate {
	_u.mutation.ResetRttMs()
	_u.mutation.SetRttMs(v)
	return _u
}

// SetNillableRttMs sets the "rtt_ms" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableRttMs(v *int) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetRttMs(*v)
	}
	return _u
}

// AddRttMs adds value to the "rtt_ms" field.
func (_u *ProxyRoutingHealthReportUpdate) AddRttMs(v int) *ProxyRoutingHealthReportUpdate {
	_u.mutation.AddRttMs(v)
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ProxyRoutingHealthReportUpdate) SetConsecutiveFailures(v int) *ProxyRoutingHealthReportUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableConsecutiveFailures(v *int) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ProxyRoutingHealthReportUpdate) AddConsecutiveFailures(v int) *ProxyRoutingHealthReportUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ProxyRoutingHealthReportUpdate) SetLastError(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableLastError(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ProxyRoutingHealthReportUpdate) ClearLastError() *ProxyRoutingHealthReportUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetOutboundTag sets the "outbound_tag" field.
func (_u *ProxyRoutingHealthReportUpdate) SetOutboundTag(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetOutboundTag(v)
	return _u
}

// SetNillableOutboundTag sets the "outbound_tag" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableOutboundTag(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetOutboundTag(*v)
	}
	return _u
}

// SetDNSResolverTag sets the "dns_resolver_tag" field.
func (_u *ProxyRoutingHealthReportUpdate) SetDNSResolverTag(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetDNSResolverTag(v)
	return _u
}

// SetNillableDNSResolverTag sets the "dns_resolver_tag" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableDNSResolverTag(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetDNSResolverTag(*v)
	}
	return _u
}

// SetCheckedAt sets the "checked_at" field.
func (_u *ProxyRoutingHealthReportUpdate) SetCheckedAt(v time.Time) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableCheckedAt(v *time.Time) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// SetReportJSON sets the "report_json" field.
func (_u *ProxyRoutingHealthReportUpdate) SetReportJSON(v string) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetReportJSON(v)
	return _u
}

// SetNillableReportJSON sets the "report_json" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdate) SetNillableReportJSON(v *string) *ProxyRoutingHealthReportUpdate {
	if v != nil {
		_u.SetReportJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyRoutingHealthReportUpdate) SetUpdatedAt(v time.Time) *ProxyRoutingHealthReportUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyRoutingHealthReportMutation object of the builder.
func (_u *ProxyRoutingHealthReportUpdate) Mutation() *ProxyRoutingHealthReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyRoutingHealthReportUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyRoutingHealthReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyRoutingHealthReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyRoutingHealthReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyRoutingHealthReportUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyroutinghealthreport.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyRoutingHealthReportUpdate) check() error {
	if v, ok := _u.mutation.ReporterType(); ok {
		if err := proxyroutinghealthreport.ReporterTypeValidator(v); err != nil {
			return &ValidationError{Name: "reporter_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.reporter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := proxyroutinghealthreport.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileCode(); ok {
		if err := proxyroutinghealthreport.ProfileCodeValidator(v); err != nil {
			return &ValidationError{Name: "profile_code", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.profile_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutingHash(); ok {
		if err := proxyroutinghealthreport.RoutingHashValidator(v); err != nil {
			return &ValidationError{Name: "routing_hash", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.routing_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := proxyroutinghealthreport.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKey(); ok {
		if err := proxyroutinghealthreport.SubjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "subject_key", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.subject_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxyroutinghealthreport.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxyroutinghealthreport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := proxyroutinghealthreport.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutboundTag(); ok {
		if err := proxyroutinghealthreport.OutboundTagValidator(v); err != nil {
			return &ValidationError{Name: "outbound_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.outbound_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DNSResolverTag(); ok {
		if err := proxyroutinghealthreport.DNSResolverTagValidator(v); err != nil {
			return &ValidationError{Name: "dns_resolver_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.dns_resolver_tag": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyRoutingHealthReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyroutinghealthreport.Table, proxyroutinghealthreport.Columns, sqlgraph.NewFieldSpec(proxyroutinghealthreport.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReporterType(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReporterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReporterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileCode(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldProfileCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingHash(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRoutingHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKey(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSubjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RttMs(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRttMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRttMs(); ok {
		_spec.AddField(proxyroutinghealthreport.FieldRttMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(proxyroutinghealthreport.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(proxyroutinghealthreport.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.OutboundTag(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldOutboundTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.DNSResolverTag(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldDNSResolverTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldCheckedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReportJSON(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReportJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyroutinghealthreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyRoutingHealthReportUpdateOne is the builder for updating a single ProxyRoutingHealthReport entity.
type ProxyRoutingHealthReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyRoutingHealthReportMutation
}

// SetReporterType sets the "reporter_type" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetReporterType(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetReporterType(v)
	return _u
}

// SetNillableReporterType sets the "reporter_type" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableReporterType(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetReporterType(*v)
	}
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetReporterID(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableReporterID(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// SetProfileCode sets the "profile_code" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetProfileCode(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetProfileCode(v)
	return _u
}

// SetNillableProfileCode sets the "profile_code" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableProfileCode(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetProfileCode(*v)
	}
	return _u
}

// SetRoutingHash sets the "routing_hash" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetRoutingHash(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetRoutingHash(v)
	return _u
}

// SetNillableRoutingHash sets the "routing_hash" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableRoutingHash(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetRoutingHash(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetSubjectType(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableSubjectType(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectKey sets the "subject_key" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetSubjectKey(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetSubjectKey(v)
	return _u
}

// SetNillableSubjectKey sets the "subject_key" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableSubjectKey(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetSubjectKey(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetRegion(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableRegion(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetStatus(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableStatus(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetSource(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableSource(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRttMs sets the "rtt_ms" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetRttMs(v int) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.ResetRttMs()
	_u.mutation.SetRttMs(v)
	return _u
}

// SetNillableRttMs sets the "rtt_ms" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableRttMs(v *int) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetRttMs(*v)
	}
	return _u
}

// AddRttMs adds value to the "rtt_ms" field.
func (_u *ProxyRoutingHealthReportUpdateOne) AddRttMs(v int) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.AddRttMs(v)
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetConsecutiveFailures(v int) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableConsecutiveFailures(v *int) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ProxyRoutingHealthReportUpdateOne) AddConsecutiveFailures(v int) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetLastError(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableLastError(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ProxyRoutingHealthReportUpdateOne) ClearLastError() *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetOutboundTag sets the "outbound_tag" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetOutboundTag(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetOutboundTag(v)
	return _u
}

// SetNillableOutboundTag sets the "outbound_tag" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableOutboundTag(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetOutboundTag(*v)
	}
	return _u
}

// SetDNSResolverTag sets the "dns_resolver_tag" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetDNSResolverTag(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetDNSResolverTag(v)
	return _u
}

// SetNillableDNSResolverTag sets the "dns_resolver_tag" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableDNSResolverTag(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetDNSResolverTag(*v)
	}
	return _u
}

// SetCheckedAt sets the "checked_at" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetCheckedAt(v time.Time) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableCheckedAt(v *time.Time) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// SetReportJSON sets the "report_json" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetReportJSON(v string) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetReportJSON(v)
	return _u
}

// SetNillableReportJSON sets the "report_json" field if the given value is not nil.
func (_u *ProxyRoutingHealthReportUpdateOne) SetNillableReportJSON(v *string) *ProxyRoutingHealthReportUpdateOne {
	if v != nil {
		_u.SetReportJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyRoutingHealthReportUpdateOne) SetUpdatedAt(v time.Time) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyRoutingHealthReportMutation object of the builder.
func (_u *ProxyRoutingHealthReportUpdateOne) Mutation() *ProxyRoutingHealthReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyRoutingHealthReportUpdate builder.
func (_u *ProxyRoutingHealthReportUpdateOne) Where(ps ...predicate.ProxyRoutingHealthReport) *ProxyRoutingHealthReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyRoutingHealthReportUpdateOne) Select(field string, fields ...string) *ProxyRoutingHealthReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyRoutingHealthReport entity.
func (_u *ProxyRoutingHealthReportUpdateOne) Save(ctx context.Context) (*ProxyRoutingHealthReport, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyRoutingHealthReportUpdateOne) SaveX(ctx context.Context) *ProxyRoutingHealthReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyRoutingHealthReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyRoutingHealthReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyRoutingHealthReportUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyroutinghealthreport.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyRoutingHealthReportUpdateOne) check() error {
	if v, ok := _u.mutation.ReporterType(); ok {
		if err := proxyroutinghealthreport.ReporterTypeValidator(v); err != nil {
			return &ValidationError{Name: "reporter_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.reporter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := proxyroutinghealthreport.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileCode(); ok {
		if err := proxyroutinghealthreport.ProfileCodeValidator(v); err != nil {
			return &ValidationError{Name: "profile_code", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.profile_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutingHash(); ok {
		if err := proxyroutinghealthreport.RoutingHashValidator(v); err != nil {
			return &ValidationError{Name: "routing_hash", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.routing_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := proxyroutinghealthreport.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKey(); ok {
		if err := proxyroutinghealthreport.SubjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "subject_key", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.subject_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxyroutinghealthreport.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxyroutinghealthreport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := proxyroutinghealthreport.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutboundTag(); ok {
		if err := proxyroutinghealthreport.OutboundTagValidator(v); err != nil {
			return &ValidationError{Name: "outbound_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.outbound_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DNSResolverTag(); ok {
		if err := proxyroutinghealthreport.DNSResolverTagValidator(v); err != nil {
			return &ValidationError{Name: "dns_resolver_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingHealthReport.dns_resolver_tag": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyRoutingHealthReportUpdateOne) sqlSave(ctx context.Context) (_node *ProxyRoutingHealthReport, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyroutinghealthreport.Table, proxyroutinghealthreport.Columns, sqlgraph.NewFieldSpec(proxyroutinghealthreport.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyRoutingHealthReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyroutinghealthreport.FieldID)
		for _, f := range fields {
			if !proxyroutinghealthreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyroutinghealthreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReporterType(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReporterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReporterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileCode(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldProfileCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingHash(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRoutingHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKey(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSubjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RttMs(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldRttMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRttMs(); ok {
		_spec.AddField(proxyroutinghealthreport.FieldRttMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(proxyroutinghealthreport.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(proxyroutinghealthreport.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.OutboundTag(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldOutboundTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.DNSResolverTag(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldDNSResolverTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldCheckedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReportJSON(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldReportJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyroutinghealthreport.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxyRoutingHealthReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyroutinghealthreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
