// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingrouteevent"
)

// ProxyRoutingRouteEventUpdate is the builder for updating ProxyRoutingRouteEvent entities.
type ProxyRoutingRouteEventUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyRoutingRouteEventMutation
}

// Where appends a list predicates to the ProxyRoutingRouteEventUpdate builder.
func (_u *ProxyRoutingRouteEventUpdate) Where(ps ...predicate.ProxyRoutingRouteEvent) *ProxyRoutingRouteEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReporterType sets the "reporter_type" field.
func (_u *ProxyRoutingRouteEventUpdate) SetReporterType(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetReporterType(v)
	return _u
}

// SetNillableReporterType sets the "reporter_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableReporterType(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetReporterType(*v)
	}
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ProxyRoutingRouteEventUpdate) SetReporterID(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableReporterID(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// SetProfileCode sets the "profile_code" field.
func (_u *ProxyRoutingRouteEventUpdate) SetProfileCode(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetProfileCode(v)
	return _u
}

// SetNillableProfileCode sets the "profile_code" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableProfileCode(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetProfileCode(*v)
	}
	return _u
}

// SetRoutingHash sets the "routing_hash" field.
func (_u *ProxyRoutingRouteEventUpdate) SetRoutingHash(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetRoutingHash(v)
	return _u
}

// SetNillableRoutingHash sets the "routing_hash" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableRoutingHash(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetRoutingHash(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ProxyRoutingRouteEventUpdate) SetEventType(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableEventType(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ProxyRoutingRouteEventUpdate) SetSubject(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableSubject(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *ProxyRoutingRouteEventUpdate) SetRuleID(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableRuleID(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetRuleName sets the "rule_name" field.
func (_u *ProxyRoutingRouteEventUpdate) SetRuleName(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetRuleName(v)
	return _u
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableRuleName(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetRuleName(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ProxyRoutingRouteEventUpdate) SetActionType(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableActionType(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetOutboundTag sets the "outbound_tag" field.
func (_u *ProxyRoutingRouteEventUpdate) SetOutboundTag(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetOutboundTag(v)
	return _u
}

// SetNillableOutboundTag sets the "outbound_tag" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableOutboundTag(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetOutboundTag(*v)
	}
	return _u
}

// SetDNSResolverTag sets the "dns_resolver_tag" field.
func (_u *ProxyRoutingRouteEventUpdate) SetDNSResolverTag(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetDNSResolverTag(v)
	return _u
}

// SetNillableDNSResolverTag sets the "dns_resolver_tag" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableDNSResolverTag(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetDNSResolverTag(*v)
	}
	return _u
}

// SetFallbackTarget sets the "fallback_target" field.
func (_u *ProxyRoutingRouteEventUpdate) SetFallbackTarget(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetFallbackTarget(v)
	return _u
}

// SetNillableFallbackTarget sets the "fallback_target" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableFallbackTarget(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetFallbackTarget(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyRoutingRouteEventUpdate) SetStatus(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableStatus(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ProxyRoutingRouteEventUpdate) SetLatencyMs(v int) *ProxyRoutingRouteEventUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableLatencyMs(v *int) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ProxyRoutingRouteEventUpdate) AddLatencyMs(v int) *ProxyRoutingRouteEventUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *ProxyRoutingRouteEventUpdate) SetError(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableError(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ProxyRoutingRouteEventUpdate) ClearError() *ProxyRoutingRouteEventUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetEventAt sets the "event_at" field.
func (_u *ProxyRoutingRouteEventUpdate) SetEventAt(v time.Time) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetEventAt(v)
	return _u
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableEventAt(v *time.Time) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetEventAt(*v)
	}
	return _u
}

// SetEventJSON sets the "event_json" field.
func (_u *ProxyRoutingRouteEventUpdate) SetEventJSON(v string) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetEventJSON(v)
	return _u
}

// SetNillableEventJSON sets the "event_json" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdate) SetNillableEventJSON(v *string) *ProxyRoutingRouteEventUpdate {
	if v != nil {
		_u.SetEventJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyRoutingRouteEventUpdate) SetUpdatedAt(v time.Time) *ProxyRoutingRouteEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyRoutingRouteEventMutation object of the builder.
func (_u *ProxyRoutingRouteEventUpdate) Mutation() *ProxyRoutingRouteEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyRoutingRouteEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyRoutingRouteEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyRoutingRouteEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyRoutingRouteEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyRoutingRouteEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyroutingrouteevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyRoutingRouteEventUpdate) check() error {
	if v, ok := _u.mutation.ReporterType(); ok {
		if err := proxyroutingrouteevent.ReporterTypeValidator(v); err != nil {
			return &ValidationError{Name: "reporter_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.reporter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := proxyroutingrouteevent.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileCode(); ok {
		if err := proxyroutingrouteevent.ProfileCodeValidator(v); err != nil {
			return &ValidationError{Name: "profile_code", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.profile_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutingHash(); ok {
		if err := proxyroutingrouteevent.RoutingHashValidator(v); err != nil {
			return &ValidationError{Name: "routing_hash", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.routing_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := proxyroutingrouteevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := proxyroutingrouteevent.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleID(); ok {
		if err := proxyroutingrouteevent.RuleIDValidator(v); err != nil {
			return &ValidationError{Name: "rule_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.rule_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleName(); ok {
		if err := proxyroutingrouteevent.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.rule_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := proxyroutingrouteevent.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutboundTag(); ok {
		if err := proxyroutingrouteevent.OutboundTagValidator(v); err != nil {
			return &ValidationError{Name: "outbound_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.outbound_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DNSResolverTag(); ok {
		if err := proxyroutingrouteevent.DNSResolverTagValidator(v); err != nil {
			return &ValidationError{Name: "dns_resolver_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.dns_resolver_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackTarget(); ok {
		if err := proxyroutingrouteevent.FallbackTargetValidator(v); err != nil {
			return &ValidationError{Name: "fallback_target", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.fallback_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxyroutingrouteevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyRoutingRouteEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyroutingrouteevent.Table, proxyroutingrouteevent.Columns, sqlgraph.NewFieldSpec(proxyroutingrouteevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReporterType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldReporterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldReporterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileCode(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldProfileCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingHash(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRoutingHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleName(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutboundTag(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldOutboundTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.DNSResolverTag(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldDNSResolverTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.FallbackTarget(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldFallbackTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(proxyroutingrouteevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(proxyroutingrouteevent.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.EventAt(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventJSON(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyroutingrouteevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyRoutingRouteEventUpdateOne is the builder for updating a single ProxyRoutingRouteEvent entity.
type ProxyRoutingRouteEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyRoutingRouteEventMutation
}

// SetReporterType sets the "reporter_type" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetReporterType(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetReporterType(v)
	return _u
}

// SetNillableReporterType sets the "reporter_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableReporterType(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetReporterType(*v)
	}
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetReporterID(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableReporterID(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// SetProfileCode sets the "profile_code" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetProfileCode(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetProfileCode(v)
	return _u
}

// SetNillableProfileCode sets the "profile_code" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableProfileCode(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetProfileCode(*v)
	}
	return _u
}

// SetRoutingHash sets the "routing_hash" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetRoutingHash(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetRoutingHash(v)
	return _u
}

// SetNillableRoutingHash sets the "routing_hash" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableRoutingHash(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetRoutingHash(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetEventType(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableEventType(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetSubject(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableSubject(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetRuleID(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableRuleID(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetRuleName sets the "rule_name" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetRuleName(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetRuleName(v)
	return _u
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableRuleName(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetRuleName(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetActionType(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableActionType(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetOutboundTag sets the "outbound_tag" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetOutboundTag(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetOutboundTag(v)
	return _u
}

// SetNillableOutboundTag sets the "outbound_tag" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableOutboundTag(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetOutboundTag(*v)
	}
	return _u
}

// SetDNSResolverTag sets the "dns_resolver_tag" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetDNSResolverTag(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetDNSResolverTag(v)
	return _u
}

// SetNillableDNSResolverTag sets the "dns_resolver_tag" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableDNSResolverTag(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetDNSResolverTag(*v)
	}
	return _u
}

// SetFallbackTarget sets the "fallback_target" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetFallbackTarget(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetFallbackTarget(v)
	return _u
}

// SetNillableFallbackTarget sets the "fallback_target" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableFallbackTarget(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetFallbackTarget(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetStatus(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableStatus(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetLatencyMs(v int) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableLatencyMs(v *int) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ProxyRoutingRouteEventUpdateOne) AddLatencyMs(v int) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetError(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableError(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ProxyRoutingRouteEventUpdateOne) ClearError() *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetEventAt sets the "event_at" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetEventAt(v time.Time) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetEventAt(v)
	return _u
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableEventAt(v *time.Time) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetEventAt(*v)
	}
	return _u
}

// SetEventJSON sets the "event_json" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetEventJSON(v string) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetEventJSON(v)
	return _u
}

// SetNillableEventJSON sets the "event_json" field if the given value is not nil.
func (_u *ProxyRoutingRouteEventUpdateOne) SetNillableEventJSON(v *string) *ProxyRoutingRouteEventUpdateOne {
	if v != nil {
		_u.SetEventJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyRoutingRouteEventUpdateOne) SetUpdatedAt(v time.Time) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyRoutingRouteEventMutation object of the builder.
func (_u *ProxyRoutingRouteEventUpdateOne) Mutation() *ProxyRoutingRouteEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyRoutingRouteEventUpdate builder.
func (_u *ProxyRoutingRouteEventUpdateOne) Where(ps ...predicate.ProxyRoutingRouteEvent) *ProxyRoutingRouteEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyRoutingRouteEventUpdateOne) Select(field string, fields ...string) *ProxyRoutingRouteEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyRoutingRouteEvent entity.
func (_u *ProxyRoutingRouteEventUpdateOne) Save(ctx context.Context) (*ProxyRoutingRouteEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyRoutingRouteEventUpdateOne) SaveX(ctx context.Context) *ProxyRoutingRouteEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyRoutingRouteEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyRoutingRouteEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyRoutingRouteEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyroutingrouteevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyRoutingRouteEventUpdateOne) check() error {
	if v, ok := _u.mutation.ReporterType(); ok {
		if err := proxyroutingrouteevent.ReporterTypeValidator(v); err != nil {
			return &ValidationError{Name: "reporter_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.reporter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := proxyroutingrouteevent.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileCode(); ok {
		if err := proxyroutingrouteevent.ProfileCodeValidator(v); err != nil {
			return &ValidationError{Name: "profile_code", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.profile_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutingHash(); ok {
		if err := proxyroutingrouteevent.RoutingHashValidator(v); err != nil {
			return &ValidationError{Name: "routing_hash", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.routing_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := proxyroutingrouteevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := proxyroutingrouteevent.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleID(); ok {
		if err := proxyroutingrouteevent.RuleIDValidator(v); err != nil {
			return &ValidationError{Name: "rule_id", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.rule_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleName(); ok {
		if err := proxyroutingrouteevent.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.rule_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := proxyroutingrouteevent.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutboundTag(); ok {
		if err := proxyroutingrouteevent.OutboundTagValidator(v); err != nil {
			return &ValidationError{Name: "outbound_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.outbound_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DNSResolverTag(); ok {
		if err := proxyroutingrouteevent.DNSResolverTagValidator(v); err != nil {
			return &ValidationError{Name: "dns_resolver_tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.dns_resolver_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackTarget(); ok {
		if err := proxyroutingrouteevent.FallbackTargetValidator(v); err != nil {
			return &ValidationError{Name: "fallback_target", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.fallback_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxyroutingrouteevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingRouteEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyRoutingRouteEventUpdateOne) sqlSave(ctx context.Context) (_node *ProxyRoutingRouteEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyroutingrouteevent.Table, proxyroutingrouteevent.Columns, sqlgraph.NewFieldSpec(proxyroutingrouteevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyRoutingRouteEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyroutingrouteevent.FieldID)
		for _, f := range fields {
			if !proxyroutingrouteevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyroutingrouteevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReporterType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldReporterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldReporterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileCode(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldProfileCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingHash(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRoutingHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleName(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldRuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutboundTag(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldOutboundTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.DNSResolverTag(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldDNSResolverTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.FallbackTarget(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldFallbackTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(proxyroutingrouteevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(proxyroutingrouteevent.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.EventAt(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventJSON(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldEventJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyroutingrouteevent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxyRoutingRouteEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyroutingrouteevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
