// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingdnsresolver"
)

// ProxyRoutingDNSResolverDelete is the builder for deleting a ProxyRoutingDNSResolver entity.
type ProxyRoutingDNSResolverDelete struct {
	config
	hooks    []Hook
	mutation *ProxyRoutingDNSResolverMutation
}

// Where appends a list predicates to the ProxyRoutingDNSResolverDelete builder.
func (_d *ProxyRoutingDNSResolverDelete) Where(ps ...predicate.ProxyRoutingDNSResolver) *ProxyRoutingDNSResolverDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyRoutingDNSResolverDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRoutingDNSResolverDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyRoutingDNSResolverDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyroutingdnsresolver.Table, sqlgraph.NewFieldSpec(proxyroutingdnsresolver.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyRoutingDNSResolverDeleteOne is the builder for deleting a single ProxyRoutingDNSResolver entity.
type ProxyRoutingDNSResolverDeleteOne struct {
	_d *ProxyRoutingDNSResolverDelete
}

// Where appends a list predicates to the ProxyRoutingDNSResolverDelete builder.
func (_d *ProxyRoutingDNSResolverDeleteOne) Where(ps ...predicate.ProxyRoutingDNSResolver) *ProxyRoutingDNSResolverDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyRoutingDNSResolverDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyroutingdnsresolver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRoutingDNSResolverDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
