// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingdnsresolver"
)

// ProxyRoutingDNSResolver is the model entity for the ProxyRoutingDNSResolver schema.
type ProxyRoutingDNSResolver struct {
	config `json:"-"`
	// ID of the ent.
	// DNS Resolver ID
	ID int64 `json:"id,omitempty"`
	// Stable resolver tag
	Tag string `json:"tag,omitempty"`
	// Resolver display name
	Name string `json:"name,omitempty"`
	// doh/dot/udp/tcp
	Proto string `json:"proto,omitempty"`
	// Resolver address
	Address string `json:"address,omitempty"`
	// Resolver port
	Port int `json:"port,omitempty"`
	// Resolver enabled
	Enabled bool `json:"enabled,omitempty"`
	// routing_profile.v1 DNS resolver JSON
	ResolverJSON string `json:"resolver_json,omitempty"`
	// Created at
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated at
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyRoutingDNSResolver) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyroutingdnsresolver.FieldEnabled:
			values[i] = new(sql.NullBool)
		case proxyroutingdnsresolver.FieldID, proxyroutingdnsresolver.FieldPort:
			values[i] = new(sql.NullInt64)
		case proxyroutingdnsresolver.FieldTag, proxyroutingdnsresolver.FieldName, proxyroutingdnsresolver.FieldProto, proxyroutingdnsresolver.FieldAddress, proxyroutingdnsresolver.FieldResolverJSON:
			values[i] = new(sql.NullString)
		case proxyroutingdnsresolver.FieldCreatedAt, proxyroutingdnsresolver.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyRoutingDNSResolver fields.
func (_m *ProxyRoutingDNSResolver) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyroutingdnsresolver.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyroutingdnsresolver.FieldTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag", values[i])
			} else if value.Valid {
				_m.Tag = value.String
			}
		case proxyroutingdnsresolver.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxyroutingdnsresolver.FieldProto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proto", values[i])
			} else if value.Valid {
				_m.Proto = value.String
			}
		case proxyroutingdnsresolver.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case proxyroutingdnsresolver.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case proxyroutingdnsresolver.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case proxyroutingdnsresolver.FieldResolverJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolver_json", values[i])
			} else if value.Valid {
				_m.ResolverJSON = value.String
			}
		case proxyroutingdnsresolver.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyroutingdnsresolver.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyRoutingDNSResolver.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyRoutingDNSResolver) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyRoutingDNSResolver.
// Note that you need to call ProxyRoutingDNSResolver.Unwrap() before calling this method if this ProxyRoutingDNSResolver
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyRoutingDNSResolver) Update() *ProxyRoutingDNSResolverUpdateOne {
	return NewProxyRoutingDNSResolverClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyRoutingDNSResolver entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyRoutingDNSResolver) Unwrap() *ProxyRoutingDNSResolver {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyRoutingDNSResolver is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyRoutingDNSResolver) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyRoutingDNSResolver(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tag=")
	builder.WriteString(_m.Tag)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("proto=")
	builder.WriteString(_m.Proto)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("resolver_json=")
	builder.WriteString(_m.ResolverJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyRoutingDNSResolvers is a parsable slice of ProxyRoutingDNSResolver.
type ProxyRoutingDNSResolvers []*ProxyRoutingDNSResolver
