// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
	"github.com/npanel-dev/NPanel-backend/ent/proxysubscribecategory"
)

// ProxySubscribeCategoryUpdate is the builder for updating ProxySubscribeCategory entities.
type ProxySubscribeCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySubscribeCategoryMutation
}

// Where appends a list predicates to the ProxySubscribeCategoryUpdate builder.
func (_u *ProxySubscribeCategoryUpdate) Where(ps ...predicate.ProxySubscribeCategory) *ProxySubscribeCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ProxySubscribeCategoryUpdate) SetParentID(v int64) *ProxySubscribeCategoryUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableParentID(v *int64) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ProxySubscribeCategoryUpdate) AddParentID(v int64) *ProxySubscribeCategoryUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscribeCategoryUpdate) SetName(v string) *ProxySubscribeCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableName(v *string) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxySubscribeCategoryUpdate) SetDescription(v string) *ProxySubscribeCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableDescription(v *string) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProxySubscribeCategoryUpdate) ClearDescription() *ProxySubscribeCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ProxySubscribeCategoryUpdate) SetLanguage(v string) *ProxySubscribeCategoryUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableLanguage(v *string) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxySubscribeCategoryUpdate) SetShow(v bool) *ProxySubscribeCategoryUpdate {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableShow(v *bool) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ProxySubscribeCategoryUpdate) SetSort(v int32) *ProxySubscribeCategoryUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdate) SetNillableSort(v *int32) *ProxySubscribeCategoryUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ProxySubscribeCategoryUpdate) AddSort(v int32) *ProxySubscribeCategoryUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscribeCategoryUpdate) SetUpdatedAt(v time.Time) *ProxySubscribeCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxySubscribeCategoryMutation object of the builder.
func (_u *ProxySubscribeCategoryUpdate) Mutation() *ProxySubscribeCategoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySubscribeCategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscribeCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySubscribeCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscribeCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscribeCategoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscribecategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscribeCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscribecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := proxysubscribecategory.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeCategory.language": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscribeCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscribecategory.Table, proxysubscribecategory.Columns, sqlgraph.NewFieldSpec(proxysubscribecategory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(proxysubscribecategory.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(proxysubscribecategory.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscribecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxysubscribecategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(proxysubscribecategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(proxysubscribecategory.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxysubscribecategory.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(proxysubscribecategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(proxysubscribecategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribecategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscribecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySubscribeCategoryUpdateOne is the builder for updating a single ProxySubscribeCategory entity.
type ProxySubscribeCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySubscribeCategoryMutation
}

// SetParentID sets the "parent_id" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetParentID(v int64) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableParentID(v *int64) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ProxySubscribeCategoryUpdateOne) AddParentID(v int64) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetName(v string) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableName(v *string) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetDescription(v string) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableDescription(v *string) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProxySubscribeCategoryUpdateOne) ClearDescription() *ProxySubscribeCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetLanguage(v string) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableLanguage(v *string) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetShow(v bool) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableShow(v *bool) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetSort(v int32) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ProxySubscribeCategoryUpdateOne) SetNillableSort(v *int32) *ProxySubscribeCategoryUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ProxySubscribeCategoryUpdateOne) AddSort(v int32) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscribeCategoryUpdateOne) SetUpdatedAt(v time.Time) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxySubscribeCategoryMutation object of the builder.
func (_u *ProxySubscribeCategoryUpdateOne) Mutation() *ProxySubscribeCategoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxySubscribeCategoryUpdate builder.
func (_u *ProxySubscribeCategoryUpdateOne) Where(ps ...predicate.ProxySubscribeCategory) *ProxySubscribeCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySubscribeCategoryUpdateOne) Select(field string, fields ...string) *ProxySubscribeCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySubscribeCategory entity.
func (_u *ProxySubscribeCategoryUpdateOne) Save(ctx context.Context) (*ProxySubscribeCategory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscribeCategoryUpdateOne) SaveX(ctx context.Context) *ProxySubscribeCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySubscribeCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscribeCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscribeCategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscribecategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscribeCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscribecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := proxysubscribecategory.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeCategory.language": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscribeCategoryUpdateOne) sqlSave(ctx context.Context) (_node *ProxySubscribeCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscribecategory.Table, proxysubscribecategory.Columns, sqlgraph.NewFieldSpec(proxysubscribecategory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySubscribeCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysubscribecategory.FieldID)
		for _, f := range fields {
			if !proxysubscribecategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysubscribecategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(proxysubscribecategory.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(proxysubscribecategory.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscribecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(proxysubscribecategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(proxysubscribecategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(proxysubscribecategory.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxysubscribecategory.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(proxysubscribecategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(proxysubscribecategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribecategory.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxySubscribeCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscribecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
