// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingoutbound"
)

// ProxyRoutingOutboundCreate is the builder for creating a ProxyRoutingOutbound entity.
type ProxyRoutingOutboundCreate struct {
	config
	mutation *ProxyRoutingOutboundMutation
	hooks    []Hook
}

// SetTag sets the "tag" field.
func (_c *ProxyRoutingOutboundCreate) SetTag(v string) *ProxyRoutingOutboundCreate {
	_c.mutation.SetTag(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProxyRoutingOutboundCreate) SetName(v string) *ProxyRoutingOutboundCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ProxyRoutingOutboundCreate) SetType(v string) *ProxyRoutingOutboundCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableType(v *string) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *ProxyRoutingOutboundCreate) SetRegion(v string) *ProxyRoutingOutboundCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableRegion(v *string) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ProxyRoutingOutboundCreate) SetEnabled(v bool) *ProxyRoutingOutboundCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableEnabled(v *bool) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetOutboundJSON sets the "outbound_json" field.
func (_c *ProxyRoutingOutboundCreate) SetOutboundJSON(v string) *ProxyRoutingOutboundCreate {
	_c.mutation.SetOutboundJSON(v)
	return _c
}

// SetNillableOutboundJSON sets the "outbound_json" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableOutboundJSON(v *string) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetOutboundJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyRoutingOutboundCreate) SetCreatedAt(v time.Time) *ProxyRoutingOutboundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableCreatedAt(v *time.Time) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyRoutingOutboundCreate) SetUpdatedAt(v time.Time) *ProxyRoutingOutboundCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyRoutingOutboundCreate) SetNillableUpdatedAt(v *time.Time) *ProxyRoutingOutboundCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyRoutingOutboundCreate) SetID(v int64) *ProxyRoutingOutboundCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyRoutingOutboundMutation object of the builder.
func (_c *ProxyRoutingOutboundCreate) Mutation() *ProxyRoutingOutboundMutation {
	return _c.mutation
}

// Save creates the ProxyRoutingOutbound in the database.
func (_c *ProxyRoutingOutboundCreate) Save(ctx context.Context) (*ProxyRoutingOutbound, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyRoutingOutboundCreate) SaveX(ctx context.Context) *ProxyRoutingOutbound {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyRoutingOutboundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyRoutingOutboundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyRoutingOutboundCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := proxyroutingoutbound.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := proxyroutingoutbound.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := proxyroutingoutbound.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.OutboundJSON(); !ok {
		v := proxyroutingoutbound.DefaultOutboundJSON
		_c.mutation.SetOutboundJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyroutingoutbound.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyroutingoutbound.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyRoutingOutboundCreate) check() error {
	if _, ok := _c.mutation.Tag(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.tag"`)}
	}
	if v, ok := _c.mutation.Tag(); ok {
		if err := proxyroutingoutbound.TagValidator(v); err != nil {
			return &ValidationError{Name: "tag", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingOutbound.tag": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxyroutingoutbound.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingOutbound.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := proxyroutingoutbound.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingOutbound.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := proxyroutingoutbound.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyRoutingOutbound.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.enabled"`)}
	}
	if _, ok := _c.mutation.OutboundJSON(); !ok {
		return &ValidationError{Name: "outbound_json", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.outbound_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyRoutingOutbound.updated_at"`)}
	}
	return nil
}

func (_c *ProxyRoutingOutboundCreate) sqlSave(ctx context.Context) (*ProxyRoutingOutbound, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyRoutingOutboundCreate) createSpec() (*ProxyRoutingOutbound, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyRoutingOutbound{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyroutingoutbound.Table, sqlgraph.NewFieldSpec(proxyroutingoutbound.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Tag(); ok {
		_spec.SetField(proxyroutingoutbound.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxyroutingoutbound.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(proxyroutingoutbound.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(proxyroutingoutbound.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(proxyroutingoutbound.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.OutboundJSON(); ok {
		_spec.SetField(proxyroutingoutbound.FieldOutboundJSON, field.TypeString, value)
		_node.OutboundJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyroutingoutbound.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyroutingoutbound.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxyRoutingOutboundCreateBulk is the builder for creating many ProxyRoutingOutbound entities in bulk.
type ProxyRoutingOutboundCreateBulk struct {
	config
	err      error
	builders []*ProxyRoutingOutboundCreate
}

// Save creates the ProxyRoutingOutbound entities in the database.
func (_c *ProxyRoutingOutboundCreateBulk) Save(ctx context.Context) ([]*ProxyRoutingOutbound, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyRoutingOutbound, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyRoutingOutboundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyRoutingOutboundCreateBulk) SaveX(ctx context.Context) []*ProxyRoutingOutbound {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyRoutingOutboundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyRoutingOutboundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
