// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingoutbound"
)

// ProxyRoutingOutbound is the model entity for the ProxyRoutingOutbound schema.
type ProxyRoutingOutbound struct {
	config `json:"-"`
	// ID of the ent.
	// Route Outbound ID
	ID int64 `json:"id,omitempty"`
	// Stable outbound tag
	Tag string `json:"tag,omitempty"`
	// Outbound display name
	Name string `json:"name,omitempty"`
	// node/node_group/external
	Type string `json:"type,omitempty"`
	// Region code
	Region string `json:"region,omitempty"`
	// Outbound enabled
	Enabled bool `json:"enabled,omitempty"`
	// routing_profile.v1 outbound JSON
	OutboundJSON string `json:"outbound_json,omitempty"`
	// Created at
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated at
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyRoutingOutbound) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyroutingoutbound.FieldEnabled:
			values[i] = new(sql.NullBool)
		case proxyroutingoutbound.FieldID:
			values[i] = new(sql.NullInt64)
		case proxyroutingoutbound.FieldTag, proxyroutingoutbound.FieldName, proxyroutingoutbound.FieldType, proxyroutingoutbound.FieldRegion, proxyroutingoutbound.FieldOutboundJSON:
			values[i] = new(sql.NullString)
		case proxyroutingoutbound.FieldCreatedAt, proxyroutingoutbound.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyRoutingOutbound fields.
func (_m *ProxyRoutingOutbound) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyroutingoutbound.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyroutingoutbound.FieldTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag", values[i])
			} else if value.Valid {
				_m.Tag = value.String
			}
		case proxyroutingoutbound.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxyroutingoutbound.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case proxyroutingoutbound.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case proxyroutingoutbound.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case proxyroutingoutbound.FieldOutboundJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_json", values[i])
			} else if value.Valid {
				_m.OutboundJSON = value.String
			}
		case proxyroutingoutbound.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyroutingoutbound.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyRoutingOutbound.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyRoutingOutbound) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyRoutingOutbound.
// Note that you need to call ProxyRoutingOutbound.Unwrap() before calling this method if this ProxyRoutingOutbound
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyRoutingOutbound) Update() *ProxyRoutingOutboundUpdateOne {
	return NewProxyRoutingOutboundClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyRoutingOutbound entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyRoutingOutbound) Unwrap() *ProxyRoutingOutbound {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyRoutingOutbound is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyRoutingOutbound) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyRoutingOutbound(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tag=")
	builder.WriteString(_m.Tag)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("outbound_json=")
	builder.WriteString(_m.OutboundJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyRoutingOutbounds is a parsable slice of ProxyRoutingOutbound.
type ProxyRoutingOutbounds []*ProxyRoutingOutbound
