// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/proxysubscribecategory"
)

// ProxySubscribeCategory is the model entity for the ProxySubscribeCategory schema.
type ProxySubscribeCategory struct {
	config `json:"-"`
	// ID of the ent.
	// 商品分类ID
	ID int64 `json:"id,omitempty"`
	// 父分类ID
	ParentID int64 `json:"parent_id,omitempty"`
	// 分类名称
	Name string `json:"name,omitempty"`
	// 分类描述
	Description *string `json:"description,omitempty"`
	// 语言
	Language string `json:"language,omitempty"`
	// 是否显示
	Show bool `json:"show,omitempty"`
	// 排序
	Sort int32 `json:"sort,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxySubscribeCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxysubscribecategory.FieldShow:
			values[i] = new(sql.NullBool)
		case proxysubscribecategory.FieldID, proxysubscribecategory.FieldParentID, proxysubscribecategory.FieldSort:
			values[i] = new(sql.NullInt64)
		case proxysubscribecategory.FieldName, proxysubscribecategory.FieldDescription, proxysubscribecategory.FieldLanguage:
			values[i] = new(sql.NullString)
		case proxysubscribecategory.FieldCreatedAt, proxysubscribecategory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxySubscribeCategory fields.
func (_m *ProxySubscribeCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxysubscribecategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxysubscribecategory.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		case proxysubscribecategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxysubscribecategory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case proxysubscribecategory.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case proxysubscribecategory.FieldShow:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show", values[i])
			} else if value.Valid {
				_m.Show = value.Bool
			}
		case proxysubscribecategory.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int32(value.Int64)
			}
		case proxysubscribecategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxysubscribecategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxySubscribeCategory.
// This includes values selected through modifiers, order, etc.
func (_m *ProxySubscribeCategory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxySubscribeCategory.
// Note that you need to call ProxySubscribeCategory.Unwrap() before calling this method if this ProxySubscribeCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxySubscribeCategory) Update() *ProxySubscribeCategoryUpdateOne {
	return NewProxySubscribeCategoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxySubscribeCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxySubscribeCategory) Unwrap() *ProxySubscribeCategory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxySubscribeCategory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxySubscribeCategory) String() string {
	var builder strings.Builder
	builder.WriteString("ProxySubscribeCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("show=")
	builder.WriteString(fmt.Sprintf("%v", _m.Show))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxySubscribeCategories is a parsable slice of ProxySubscribeCategory.
type ProxySubscribeCategories []*ProxySubscribeCategory
