// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutingunlockservice"
)

// ProxyRoutingUnlockService is the model entity for the ProxyRoutingUnlockService schema.
type ProxyRoutingUnlockService struct {
	config `json:"-"`
	// ID of the ent.
	// Unlock Service ID
	ID int64 `json:"id,omitempty"`
	// Stable service code
	Code string `json:"code,omitempty"`
	// Service display name
	Name string `json:"name,omitempty"`
	// Service category
	Category string `json:"category,omitempty"`
	// Service enabled
	Enabled bool `json:"enabled,omitempty"`
	// routing_profile.v1 unlock service JSON
	ServiceJSON string `json:"service_json,omitempty"`
	// Created at
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated at
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyRoutingUnlockService) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyroutingunlockservice.FieldEnabled:
			values[i] = new(sql.NullBool)
		case proxyroutingunlockservice.FieldID:
			values[i] = new(sql.NullInt64)
		case proxyroutingunlockservice.FieldCode, proxyroutingunlockservice.FieldName, proxyroutingunlockservice.FieldCategory, proxyroutingunlockservice.FieldServiceJSON:
			values[i] = new(sql.NullString)
		case proxyroutingunlockservice.FieldCreatedAt, proxyroutingunlockservice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyRoutingUnlockService fields.
func (_m *ProxyRoutingUnlockService) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyroutingunlockservice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyroutingunlockservice.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case proxyroutingunlockservice.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxyroutingunlockservice.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case proxyroutingunlockservice.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case proxyroutingunlockservice.FieldServiceJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_json", values[i])
			} else if value.Valid {
				_m.ServiceJSON = value.String
			}
		case proxyroutingunlockservice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyroutingunlockservice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyRoutingUnlockService.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyRoutingUnlockService) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyRoutingUnlockService.
// Note that you need to call ProxyRoutingUnlockService.Unwrap() before calling this method if this ProxyRoutingUnlockService
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyRoutingUnlockService) Update() *ProxyRoutingUnlockServiceUpdateOne {
	return NewProxyRoutingUnlockServiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyRoutingUnlockService entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyRoutingUnlockService) Unwrap() *ProxyRoutingUnlockService {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyRoutingUnlockService is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyRoutingUnlockService) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyRoutingUnlockService(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("service_json=")
	builder.WriteString(_m.ServiceJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyRoutingUnlockServices is a parsable slice of ProxyRoutingUnlockService.
type ProxyRoutingUnlockServices []*ProxyRoutingUnlockService
