// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/proxyroutinggrayrelease"
)

// ProxyRoutingGrayRelease is the model entity for the ProxyRoutingGrayRelease schema.
type ProxyRoutingGrayRelease struct {
	config `json:"-"`
	// ID of the ent.
	// Routing gray release ID
	ID int64 `json:"id,omitempty"`
	// Routing profile code
	ProfileCode string `json:"profile_code,omitempty"`
	// Gray release name
	Name string `json:"name,omitempty"`
	// draft/running/paused/completed/rolled_back
	Status string `json:"status,omitempty"`
	// Current gray batch number
	BatchNo int `json:"batch_no,omitempty"`
	// user/user_subscribe/subscribe/node
	TargetType string `json:"target_type,omitempty"`
	// Target IDs JSON array
	TargetIdsJSON string `json:"target_ids_json,omitempty"`
	// Operator
	Operator string `json:"operator,omitempty"`
	// Rollback reason
	RollbackReason string `json:"rollback_reason,omitempty"`
	// Started at
	StartedAt time.Time `json:"started_at,omitempty"`
	// Ended at
	EndedAt time.Time `json:"ended_at,omitempty"`
	// Release metadata JSON
	ReleaseJSON string `json:"release_json,omitempty"`
	// Created at
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated at
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyRoutingGrayRelease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyroutinggrayrelease.FieldID, proxyroutinggrayrelease.FieldBatchNo:
			values[i] = new(sql.NullInt64)
		case proxyroutinggrayrelease.FieldProfileCode, proxyroutinggrayrelease.FieldName, proxyroutinggrayrelease.FieldStatus, proxyroutinggrayrelease.FieldTargetType, proxyroutinggrayrelease.FieldTargetIdsJSON, proxyroutinggrayrelease.FieldOperator, proxyroutinggrayrelease.FieldRollbackReason, proxyroutinggrayrelease.FieldReleaseJSON:
			values[i] = new(sql.NullString)
		case proxyroutinggrayrelease.FieldStartedAt, proxyroutinggrayrelease.FieldEndedAt, proxyroutinggrayrelease.FieldCreatedAt, proxyroutinggrayrelease.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyRoutingGrayRelease fields.
func (_m *ProxyRoutingGrayRelease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyroutinggrayrelease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyroutinggrayrelease.FieldProfileCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_code", values[i])
			} else if value.Valid {
				_m.ProfileCode = value.String
			}
		case proxyroutinggrayrelease.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxyroutinggrayrelease.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case proxyroutinggrayrelease.FieldBatchNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_no", values[i])
			} else if value.Valid {
				_m.BatchNo = int(value.Int64)
			}
		case proxyroutinggrayrelease.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case proxyroutinggrayrelease.FieldTargetIdsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_ids_json", values[i])
			} else if value.Valid {
				_m.TargetIdsJSON = value.String
			}
		case proxyroutinggrayrelease.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = value.String
			}
		case proxyroutinggrayrelease.FieldRollbackReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rollback_reason", values[i])
			} else if value.Valid {
				_m.RollbackReason = value.String
			}
		case proxyroutinggrayrelease.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case proxyroutinggrayrelease.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = value.Time
			}
		case proxyroutinggrayrelease.FieldReleaseJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_json", values[i])
			} else if value.Valid {
				_m.ReleaseJSON = value.String
			}
		case proxyroutinggrayrelease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyroutinggrayrelease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyRoutingGrayRelease.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyRoutingGrayRelease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyRoutingGrayRelease.
// Note that you need to call ProxyRoutingGrayRelease.Unwrap() before calling this method if this ProxyRoutingGrayRelease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyRoutingGrayRelease) Update() *ProxyRoutingGrayReleaseUpdateOne {
	return NewProxyRoutingGrayReleaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyRoutingGrayRelease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyRoutingGrayRelease) Unwrap() *ProxyRoutingGrayRelease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyRoutingGrayRelease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyRoutingGrayRelease) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyRoutingGrayRelease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_code=")
	builder.WriteString(_m.ProfileCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("batch_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchNo))
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_ids_json=")
	builder.WriteString(_m.TargetIdsJSON)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(_m.Operator)
	builder.WriteString(", ")
	builder.WriteString("rollback_reason=")
	builder.WriteString(_m.RollbackReason)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ended_at=")
	builder.WriteString(_m.EndedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("release_json=")
	builder.WriteString(_m.ReleaseJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyRoutingGrayReleases is a parsable slice of ProxyRoutingGrayRelease.
type ProxyRoutingGrayReleases []*ProxyRoutingGrayRelease
