// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/ticket/v1/ticket.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdateTicketStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTicketStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTicketStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTicketStatusRequestMultiError, or nil if none found.
func (m *UpdateTicketStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTicketStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateTicketStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateTicketStatusRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateTicketStatusRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateTicketStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTicketStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTicketStatusRequestMultiError) AllErrors() []error { return m }

// UpdateTicketStatusRequestValidationError is the validation error returned by
// UpdateTicketStatusRequest.Validate if the designated constraints aren't met.
type UpdateTicketStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTicketStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTicketStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTicketStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTicketStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTicketStatusRequestValidationError) ErrorName() string {
	return "UpdateTicketStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTicketStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTicketStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTicketStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTicketStatusRequestValidationError{}

// Validate checks the field values on UpdateTicketStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTicketStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTicketStatusReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTicketStatusReplyMultiError, or nil if none found.
func (m *UpdateTicketStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTicketStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return UpdateTicketStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateTicketStatusReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateTicketStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateTicketStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTicketStatusReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTicketStatusReplyMultiError) AllErrors() []error { return m }

// UpdateTicketStatusReplyValidationError is the validation error returned by
// UpdateTicketStatusReply.Validate if the designated constraints aren't met.
type UpdateTicketStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTicketStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTicketStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTicketStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTicketStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTicketStatusReplyValidationError) ErrorName() string {
	return "UpdateTicketStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTicketStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTicketStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTicketStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTicketStatusReplyValidationError{}

// Validate checks the field values on GetTicketRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTicketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTicketRequestMultiError, or nil if none found.
func (m *GetTicketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTicketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetTicketRequestMultiError(errors)
	}

	return nil
}

// GetTicketRequestMultiError is an error wrapping multiple validation errors
// returned by GetTicketRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTicketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTicketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTicketRequestMultiError) AllErrors() []error { return m }

// GetTicketRequestValidationError is the validation error returned by
// GetTicketRequest.Validate if the designated constraints aren't met.
type GetTicketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTicketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTicketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTicketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTicketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTicketRequestValidationError) ErrorName() string { return "GetTicketRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetTicketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTicketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTicketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTicketRequestValidationError{}

// Validate checks the field values on GetTicketReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTicketReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTicketReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetTicketReplyMultiError,
// or nil if none found.
func (m *GetTicketReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTicketReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTicketReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTicketReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTicketReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTicketReplyMultiError(errors)
	}

	return nil
}

// GetTicketReplyMultiError is an error wrapping multiple validation errors
// returned by GetTicketReply.ValidateAll() if the designated constraints
// aren't met.
type GetTicketReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTicketReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTicketReplyMultiError) AllErrors() []error { return m }

// GetTicketReplyValidationError is the validation error returned by
// GetTicketReply.Validate if the designated constraints aren't met.
type GetTicketReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTicketReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTicketReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTicketReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTicketReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTicketReplyValidationError) ErrorName() string { return "GetTicketReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetTicketReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTicketReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTicketReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTicketReplyValidationError{}

// Validate checks the field values on TicketInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TicketInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TicketInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TicketInfoMultiError, or
// nil if none found.
func (m *TicketInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TicketInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for UserId

	for idx, item := range m.GetFollow() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TicketInfoValidationError{
						field:  fmt.Sprintf("Follow[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TicketInfoValidationError{
						field:  fmt.Sprintf("Follow[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TicketInfoValidationError{
					field:  fmt.Sprintf("Follow[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return TicketInfoMultiError(errors)
	}

	return nil
}

// TicketInfoMultiError is an error wrapping multiple validation errors
// returned by TicketInfo.ValidateAll() if the designated constraints aren't met.
type TicketInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TicketInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TicketInfoMultiError) AllErrors() []error { return m }

// TicketInfoValidationError is the validation error returned by
// TicketInfo.Validate if the designated constraints aren't met.
type TicketInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TicketInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TicketInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TicketInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TicketInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TicketInfoValidationError) ErrorName() string { return "TicketInfoValidationError" }

// Error satisfies the builtin error interface
func (e TicketInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTicketInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TicketInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TicketInfoValidationError{}

// Validate checks the field values on TicketFollow with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TicketFollow) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TicketFollow with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TicketFollowMultiError, or
// nil if none found.
func (m *TicketFollow) ValidateAll() error {
	return m.validate(true)
}

func (m *TicketFollow) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TicketId

	// no validation rules for From

	// no validation rules for Type

	// no validation rules for Content

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return TicketFollowMultiError(errors)
	}

	return nil
}

// TicketFollowMultiError is an error wrapping multiple validation errors
// returned by TicketFollow.ValidateAll() if the designated constraints aren't met.
type TicketFollowMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TicketFollowMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TicketFollowMultiError) AllErrors() []error { return m }

// TicketFollowValidationError is the validation error returned by
// TicketFollow.Validate if the designated constraints aren't met.
type TicketFollowValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TicketFollowValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TicketFollowValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TicketFollowValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TicketFollowValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TicketFollowValidationError) ErrorName() string { return "TicketFollowValidationError" }

// Error satisfies the builtin error interface
func (e TicketFollowValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTicketFollow.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TicketFollowValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TicketFollowValidationError{}

// Validate checks the field values on CreateTicketFollowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTicketFollowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTicketFollowRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTicketFollowRequestMultiError, or nil if none found.
func (m *CreateTicketFollowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTicketFollowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TicketId

	// no validation rules for From

	// no validation rules for Type

	// no validation rules for Content

	if len(errors) > 0 {
		return CreateTicketFollowRequestMultiError(errors)
	}

	return nil
}

// CreateTicketFollowRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTicketFollowRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateTicketFollowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTicketFollowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTicketFollowRequestMultiError) AllErrors() []error { return m }

// CreateTicketFollowRequestValidationError is the validation error returned by
// CreateTicketFollowRequest.Validate if the designated constraints aren't met.
type CreateTicketFollowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTicketFollowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTicketFollowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTicketFollowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTicketFollowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTicketFollowRequestValidationError) ErrorName() string {
	return "CreateTicketFollowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTicketFollowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTicketFollowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTicketFollowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTicketFollowRequestValidationError{}

// Validate checks the field values on CreateTicketFollowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTicketFollowReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTicketFollowReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTicketFollowReplyMultiError, or nil if none found.
func (m *CreateTicketFollowReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTicketFollowReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return CreateTicketFollowReplyMultiError(errors)
	}

	return nil
}

// CreateTicketFollowReplyMultiError is an error wrapping multiple validation
// errors returned by CreateTicketFollowReply.ValidateAll() if the designated
// constraints aren't met.
type CreateTicketFollowReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTicketFollowReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTicketFollowReplyMultiError) AllErrors() []error { return m }

// CreateTicketFollowReplyValidationError is the validation error returned by
// CreateTicketFollowReply.Validate if the designated constraints aren't met.
type CreateTicketFollowReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTicketFollowReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTicketFollowReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTicketFollowReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTicketFollowReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTicketFollowReplyValidationError) ErrorName() string {
	return "CreateTicketFollowReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTicketFollowReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTicketFollowReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTicketFollowReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTicketFollowReplyValidationError{}

// Validate checks the field values on GetTicketListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTicketListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTicketListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTicketListRequestMultiError, or nil if none found.
func (m *GetTicketListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTicketListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for UserId

	// no validation rules for Status

	// no validation rules for Search

	if len(errors) > 0 {
		return GetTicketListRequestMultiError(errors)
	}

	return nil
}

// GetTicketListRequestMultiError is an error wrapping multiple validation
// errors returned by GetTicketListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTicketListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTicketListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTicketListRequestMultiError) AllErrors() []error { return m }

// GetTicketListRequestValidationError is the validation error returned by
// GetTicketListRequest.Validate if the designated constraints aren't met.
type GetTicketListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTicketListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTicketListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTicketListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTicketListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTicketListRequestValidationError) ErrorName() string {
	return "GetTicketListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTicketListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTicketListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTicketListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTicketListRequestValidationError{}

// Validate checks the field values on GetTicketListData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTicketListData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTicketListData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTicketListDataMultiError, or nil if none found.
func (m *GetTicketListData) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTicketListData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTicketListDataValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTicketListDataValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTicketListDataValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetTicketListDataMultiError(errors)
	}

	return nil
}

// GetTicketListDataMultiError is an error wrapping multiple validation errors
// returned by GetTicketListData.ValidateAll() if the designated constraints
// aren't met.
type GetTicketListDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTicketListDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTicketListDataMultiError) AllErrors() []error { return m }

// GetTicketListDataValidationError is the validation error returned by
// GetTicketListData.Validate if the designated constraints aren't met.
type GetTicketListDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTicketListDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTicketListDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTicketListDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTicketListDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTicketListDataValidationError) ErrorName() string {
	return "GetTicketListDataValidationError"
}

// Error satisfies the builtin error interface
func (e GetTicketListDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTicketListData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTicketListDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTicketListDataValidationError{}

// Validate checks the field values on GetTicketListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTicketListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTicketListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTicketListReplyMultiError, or nil if none found.
func (m *GetTicketListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTicketListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTicketListReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTicketListReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTicketListReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTicketListReplyMultiError(errors)
	}

	return nil
}

// GetTicketListReplyMultiError is an error wrapping multiple validation errors
// returned by GetTicketListReply.ValidateAll() if the designated constraints
// aren't met.
type GetTicketListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTicketListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTicketListReplyMultiError) AllErrors() []error { return m }

// GetTicketListReplyValidationError is the validation error returned by
// GetTicketListReply.Validate if the designated constraints aren't met.
type GetTicketListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTicketListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTicketListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTicketListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTicketListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTicketListReplyValidationError) ErrorName() string {
	return "GetTicketListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetTicketListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTicketListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTicketListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTicketListReplyValidationError{}
