// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: public/subscription/v1/subscription.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSubscribeConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscribeConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscribeConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscribeConfigRequestMultiError, or nil if none found.
func (m *GetSubscribeConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscribeConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Flag

	// no validation rules for Token

	// no validation rules for Type

	// no validation rules for Ua

	// no validation rules for Params

	if len(errors) > 0 {
		return GetSubscribeConfigRequestMultiError(errors)
	}

	return nil
}

// GetSubscribeConfigRequestMultiError is an error wrapping multiple validation
// errors returned by GetSubscribeConfigRequest.ValidateAll() if the
// designated constraints aren't met.
type GetSubscribeConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscribeConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscribeConfigRequestMultiError) AllErrors() []error { return m }

// GetSubscribeConfigRequestValidationError is the validation error returned by
// GetSubscribeConfigRequest.Validate if the designated constraints aren't met.
type GetSubscribeConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscribeConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscribeConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscribeConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscribeConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscribeConfigRequestValidationError) ErrorName() string {
	return "GetSubscribeConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscribeConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscribeConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscribeConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscribeConfigRequestValidationError{}

// Validate checks the field values on GetSubscribeConfigReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscribeConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscribeConfigReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscribeConfigReplyMultiError, or nil if none found.
func (m *GetSubscribeConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscribeConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Config

	// no validation rules for Header

	if len(errors) > 0 {
		return GetSubscribeConfigReplyMultiError(errors)
	}

	return nil
}

// GetSubscribeConfigReplyMultiError is an error wrapping multiple validation
// errors returned by GetSubscribeConfigReply.ValidateAll() if the designated
// constraints aren't met.
type GetSubscribeConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscribeConfigReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscribeConfigReplyMultiError) AllErrors() []error { return m }

// GetSubscribeConfigReplyValidationError is the validation error returned by
// GetSubscribeConfigReply.Validate if the designated constraints aren't met.
type GetSubscribeConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscribeConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscribeConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscribeConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscribeConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscribeConfigReplyValidationError) ErrorName() string {
	return "GetSubscribeConfigReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscribeConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscribeConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscribeConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscribeConfigReplyValidationError{}
