// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: public/ticket/v1/ticket.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateUserTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserTicketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserTicketRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserTicketRequestMultiError, or nil if none found.
func (m *CreateUserTicketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserTicketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Description

	if len(errors) > 0 {
		return CreateUserTicketRequestMultiError(errors)
	}

	return nil
}

// CreateUserTicketRequestMultiError is an error wrapping multiple validation
// errors returned by CreateUserTicketRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateUserTicketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserTicketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserTicketRequestMultiError) AllErrors() []error { return m }

// CreateUserTicketRequestValidationError is the validation error returned by
// CreateUserTicketRequest.Validate if the designated constraints aren't met.
type CreateUserTicketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserTicketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserTicketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserTicketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserTicketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserTicketRequestValidationError) ErrorName() string {
	return "CreateUserTicketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserTicketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserTicketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserTicketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserTicketRequestValidationError{}

// Validate checks the field values on GetUserTicketListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserTicketListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserTicketListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserTicketListRequestMultiError, or nil if none found.
func (m *GetUserTicketListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserTicketListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Search

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return GetUserTicketListRequestMultiError(errors)
	}

	return nil
}

// GetUserTicketListRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserTicketListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserTicketListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserTicketListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserTicketListRequestMultiError) AllErrors() []error { return m }

// GetUserTicketListRequestValidationError is the validation error returned by
// GetUserTicketListRequest.Validate if the designated constraints aren't met.
type GetUserTicketListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserTicketListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserTicketListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserTicketListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserTicketListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserTicketListRequestValidationError) ErrorName() string {
	return "GetUserTicketListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserTicketListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserTicketListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserTicketListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserTicketListRequestValidationError{}

// Validate checks the field values on GetUserTicketListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserTicketListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserTicketListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserTicketListReplyMultiError, or nil if none found.
func (m *GetUserTicketListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserTicketListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserTicketListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserTicketListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserTicketListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserTicketListReplyMultiError(errors)
	}

	return nil
}

// GetUserTicketListReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserTicketListReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserTicketListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserTicketListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserTicketListReplyMultiError) AllErrors() []error { return m }

// GetUserTicketListReplyValidationError is the validation error returned by
// GetUserTicketListReply.Validate if the designated constraints aren't met.
type GetUserTicketListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserTicketListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserTicketListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserTicketListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserTicketListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserTicketListReplyValidationError) ErrorName() string {
	return "GetUserTicketListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserTicketListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserTicketListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserTicketListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserTicketListReplyValidationError{}

// Validate checks the field values on GetUserTicketDetailsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserTicketDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserTicketDetailsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserTicketDetailsRequestMultiError, or nil if none found.
func (m *GetUserTicketDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserTicketDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetUserTicketDetailsRequestMultiError(errors)
	}

	return nil
}

// GetUserTicketDetailsRequestMultiError is an error wrapping multiple
// validation errors returned by GetUserTicketDetailsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetUserTicketDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserTicketDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserTicketDetailsRequestMultiError) AllErrors() []error { return m }

// GetUserTicketDetailsRequestValidationError is the validation error returned
// by GetUserTicketDetailsRequest.Validate if the designated constraints
// aren't met.
type GetUserTicketDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserTicketDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserTicketDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserTicketDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserTicketDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserTicketDetailsRequestValidationError) ErrorName() string {
	return "GetUserTicketDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserTicketDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserTicketDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserTicketDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserTicketDetailsRequestValidationError{}

// Validate checks the field values on UpdateUserTicketStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserTicketStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserTicketStatusRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateUserTicketStatusRequestMultiError, or nil if none found.
func (m *UpdateUserTicketStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserTicketStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return UpdateUserTicketStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateUserTicketStatusRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateUserTicketStatusRequest.ValidateAll()
// if the designated constraints aren't met.
type UpdateUserTicketStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserTicketStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserTicketStatusRequestMultiError) AllErrors() []error { return m }

// UpdateUserTicketStatusRequestValidationError is the validation error
// returned by UpdateUserTicketStatusRequest.Validate if the designated
// constraints aren't met.
type UpdateUserTicketStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserTicketStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserTicketStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserTicketStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserTicketStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserTicketStatusRequestValidationError) ErrorName() string {
	return "UpdateUserTicketStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserTicketStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserTicketStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserTicketStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserTicketStatusRequestValidationError{}

// Validate checks the field values on CreateUserTicketFollowRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserTicketFollowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserTicketFollowRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateUserTicketFollowRequestMultiError, or nil if none found.
func (m *CreateUserTicketFollowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserTicketFollowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TicketId

	// no validation rules for From

	// no validation rules for Type

	// no validation rules for Content

	if len(errors) > 0 {
		return CreateUserTicketFollowRequestMultiError(errors)
	}

	return nil
}

// CreateUserTicketFollowRequestMultiError is an error wrapping multiple
// validation errors returned by CreateUserTicketFollowRequest.ValidateAll()
// if the designated constraints aren't met.
type CreateUserTicketFollowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserTicketFollowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserTicketFollowRequestMultiError) AllErrors() []error { return m }

// CreateUserTicketFollowRequestValidationError is the validation error
// returned by CreateUserTicketFollowRequest.Validate if the designated
// constraints aren't met.
type CreateUserTicketFollowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserTicketFollowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserTicketFollowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserTicketFollowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserTicketFollowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserTicketFollowRequestValidationError) ErrorName() string {
	return "CreateUserTicketFollowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserTicketFollowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserTicketFollowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserTicketFollowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserTicketFollowRequestValidationError{}

// Validate checks the field values on TicketInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TicketInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TicketInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TicketInfoMultiError, or
// nil if none found.
func (m *TicketInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TicketInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for UserId

	for idx, item := range m.GetFollow() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TicketInfoValidationError{
						field:  fmt.Sprintf("Follow[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TicketInfoValidationError{
						field:  fmt.Sprintf("Follow[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TicketInfoValidationError{
					field:  fmt.Sprintf("Follow[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return TicketInfoMultiError(errors)
	}

	return nil
}

// TicketInfoMultiError is an error wrapping multiple validation errors
// returned by TicketInfo.ValidateAll() if the designated constraints aren't met.
type TicketInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TicketInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TicketInfoMultiError) AllErrors() []error { return m }

// TicketInfoValidationError is the validation error returned by
// TicketInfo.Validate if the designated constraints aren't met.
type TicketInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TicketInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TicketInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TicketInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TicketInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TicketInfoValidationError) ErrorName() string { return "TicketInfoValidationError" }

// Error satisfies the builtin error interface
func (e TicketInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTicketInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TicketInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TicketInfoValidationError{}

// Validate checks the field values on TicketFollow with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TicketFollow) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TicketFollow with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TicketFollowMultiError, or
// nil if none found.
func (m *TicketFollow) ValidateAll() error {
	return m.validate(true)
}

func (m *TicketFollow) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TicketId

	// no validation rules for From

	// no validation rules for Type

	// no validation rules for Content

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return TicketFollowMultiError(errors)
	}

	return nil
}

// TicketFollowMultiError is an error wrapping multiple validation errors
// returned by TicketFollow.ValidateAll() if the designated constraints aren't met.
type TicketFollowMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TicketFollowMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TicketFollowMultiError) AllErrors() []error { return m }

// TicketFollowValidationError is the validation error returned by
// TicketFollow.Validate if the designated constraints aren't met.
type TicketFollowValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TicketFollowValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TicketFollowValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TicketFollowValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TicketFollowValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TicketFollowValidationError) ErrorName() string { return "TicketFollowValidationError" }

// Error satisfies the builtin error interface
func (e TicketFollowValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTicketFollow.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TicketFollowValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TicketFollowValidationError{}
